axelor-human-resource/src/main/resources/views/LeaveRequest.xml
Outside of draft status, fields are now set to read only after loading the
leave request form. A manager can still change them while the request
awaits validation.
=> RM7057 leave request : readonly fields

axelor-base/src/main/java/com/axelor/apps/base/service/administration/SequenceService.java, axelor-human-resource/src/main/resources/views/TimesheetLine.xml, axelor-project/src/main/resources/views/ProjectTask.xml
In TimesheetLine, when project/task is changed, reset the activity if
the activity does not belong to the project/task.
=> RM7130 TimeSheet: reset activity on project change

axelor-bank-payment/src/main/resources/views/BankOrder.xml, axelor-bank-payment/src/main/resources/views/Selects.xml
Added "Other" in the partner selection. If "Other" is selected, the
partner must not be a supplier, an employee a customer or a contact in
order to be selected in the lines.
=> RM7251: In BankOrder, new partner type select

axelor-base/src/main/resources/views/Product.xml, axelor-stock/src/main/java/com/axelor/apps/stock/service/LocationLineServiceImpl.java, axelor-stock/src/main/java/com/axelor/apps/stock/service/LocationService.java, axelor-stock/src/main/java/com/axelor/apps/stock/service/LocationServiceImpl.java, axelor-stock/src/main/java/com/axelor/apps/stock/service/StockMoveLineService.java, axelor-stock/src/main/java/com/axelor/apps/stock/service/StockMoveLineServiceImpl.java, axelor-stock/src/main/resources/domains/LocationLine.xml, axelor-stock/src/main/resources/domains/Product.xml, axelor-stock/src/main/resources/i18n/messages.csv, axelor-stock/src/main/resources/i18n/messages_en.csv, axelor-stock/src/main/resources/i18n/messages_fr.csv, axelor-stock/src/main/resources/views/Charts.xml, axelor-stock/src/main/resources/views/Dashboard.xml, axelor-stock/src/main/resources/views/LocationLine.xml, axelor-stock/src/main/resources/views/Product.xml, axelor-stock/src/main/resources/views/StockMoveLine.xml, axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/StockMoveServiceSupplychainImpl.java
+ Added an average price in a Location Line.
+ The average price is updated with every stock move.
+ When a stock move is cancelled, the average price goes back to the
right value.
+ Added an average price in product. This average price comes from the
stock.
+ To get average price and total in stocks for product, we take into
account external and internal locations instead of just internal.
+ For prices in product/stock, and stock move line, the scale is setted
dynamically using the configuration when it is possible, otherwise we
use scale = 2.
=> RM7102: Average price in stock for Product

axelor-exception/src/main/java/com/axelor/exception/ResponseMessageType.java, axelor-exception/src/main/java/com/axelor/exception/service/TraceBackService.java
Allow to specify the type of response message (information, warning,
error, or notification).
=> TraceBackService: add ResponseMessageType parameter

axelor-bank-payment/src/main/resources/views/BankOrder.xml
Add canView="false" on differently field in bank-order-form form:
* All BankDetails
* Partner
* Economic reason
* Receiver country
* Currencies
=> Fix Feature #8532 : Remove canView in BankOrder

axelor-bank-payment/src/main/resources/views/BankStatement.xml
IE11 doesn't support the startsWith method. Use indexOf instead.
=> RM9415: fix afb120 bank statement lines not appearing in IE11.

axelor-project/src/main/java/com/axelor/apps/project/web/ProjectController.java
Response.setValues(Object) no longer accepts unmanaged model objects.
See RM9617.
=> RM9858: fix project generation from partner.

axelor-bank-payment/src/main/resources/views/EbicsUser.xml
remove associatedUser part of fullName when userType is "transport".
=> RM9780: Display associatedUser only when userType is "signatory",

axelor-account/src/main/java/com/axelor/apps/account/web/AppAccountController.java
This should fix an NPE when clicking on “Compute payers quality” in app account configuration
=> account: fix NPE on payer quality generation

axelor-bank-payment/build.gradle
It seems that the dependency used to be pulled by another mean but this
is not the case anymore.
This fix a build failure because of classes from
org.apache.xml.security.* not being found.
=> bank-payment: add explicit dependency on apache santuario

axelor-bank-payment/build.gradle
This fix an issue where you've to manually run xjc (or anything
triggering it) to actually have all needed sources (this makes eclipse
target working out of the box).
=> bank-payment: always run xjc after generateCode

axelor-base/src/main/resources/views/Partner.xml
Contact email was truncated to half of the available space. This seems to be due to the fact that <editor/> creates a new width reference. Setting colSpan to 12 for the field allows to fill the space.
=> Adjust colSpan of contact email

axelor-account/src/main/resources/domains/AccountingReport.xml, axelor-account/src/main/resources/i18n/messages.csv, axelor-account/src/main/resources/i18n/messages_en.csv, axelor-account/src/main/resources/i18n/messages_fr.csv
Maybe it's just me, but it seems that "Creation date" doesn't bring to the attention of the user that the report won't take into account any information after the filled in date.
Renaming to closing date seems more intuitive.
=> AccountingReport: Clarify the meaning of date_val

axelor-account/src/main/java/com/axelor/apps/account/db/repo/PartnerAccountRepository.java
Remove the need to save partner twice in order to have its accounting situations populated
=> partner: accounting situations on save

axelor-stock/src/main/resources/views/StockMove.xml, axelor-supplychain/src/main/resources/views/StockMove.xml
Change dummy fields "$supplierStockMoveToInvoice" and
"$customerStockMoveToInvoice" to normal fields to allow javascript
evaluation on branch 4.1. See issue #7455
=> RM9213: Rework mass stock move UI

axelor-account/src/main/java/com/axelor/apps/account/service/AccountCustomerService.java, axelor-account/src/main/java/com/axelor/apps/account/service/invoice/workflow/ventilate/VentilateState.java, axelor-account/src/main/java/com/axelor/apps/account/service/move/MoveToolService.java, axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/service/bankorder/BankOrderMoveServiceImpl.java, axelor-human-resource/src/main/java/com/axelor/apps/hr/service/expense/ExpenseServiceImpl.java
AccountingSituation::get{Customer,Supplier,Employee}Account should never
be used directly except in AccountingSituationService, in order to
correctly fallback to accounts defined on company level if there's no
account defined on specific partner.
=> accounting: correctly fallback to global params if partner is empty

axelor-base/src/main/resources/views/User.xml
This fixes a "Name cannot be null" error when attempting to fill details upon creation
=> user: hide contact info pane if new

axelor-base/src/main/resources/views/Product.xml
Reverts axelor/axelor-business-suite#1607
The issue is more complex. The goal is to put in readonly the stock unit of a product if there is already a stock quantity in a stock location. Currently this readonly attribute doesn't appears because readonlyIf condition is wrong.
We can have a unit for service product. The standard behavior is to have only one unit (used for stocks, sales, purchases, project...). In option we can enable sales unit and purchase unit.
The unit should be copied on stock location line when creating it and if we update unit on product, we have to compare and convert (with button to propagate on stock location) and when we do a stock move we have to use the latest product unit and convert when we update stock location.
This feature will be done on the next version …
=> Revert "Product unit cannot be set"

axelor-sale/src/main/java/com/axelor/apps/sale/service/saleorder/SaleOrderWorkflowServiceImpl.java
This could lead to inconsistencies wrt JPA persistence layer if the
Service is initialized from another transation than the one that'll call
confirmOrder (“Detached entity passed to persist”)
needed for axelor/axelor-addons#7
=> sales: do not store current user as member variable

axelor-production/src/main/java/com/axelor/apps/production/service/SaleOrderWorkflowServiceProductionImpl.java, axelor-sale/src/main/java/com/axelor/apps/sale/service/saleorder/SaleOrderWorkflowService.java, axelor-sale/src/main/java/com/axelor/apps/sale/service/saleorder/SaleOrderWorkflowServiceImpl.java, axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/SaleOrderWorkflowServiceSupplychainImpl.java
Remove throws Exception as it is actually never used, only AxelorException is thrown. Avoid
having a too wide throws declaration to leverage calling code structure (needed for axelor/axelor-addons#7)
=> sales: don't use Exception on workflow method

axelor-account/src/main/resources/reports/Invoice.rptdesign, axelor-sale/src/main/resources/reports/SaleOrder.rptdesign
Fix font on invoices to have the same presentation as sale orders, fix
hidden expression for description title (it was never displayed)
=> invoice & order: properly display "note" title

axelor-base/src/main/java/com/axelor/apps/base/db/repo/ProductBaseRepository.java
Add an unbreakable space after closing square bracket in product's fullname to improve readablity
=> product: improve fullname readability

axelor-purchase/src/main/resources/views/PurchaseOrder.xml
Merge commit b0f38e6 seems to have been down after a hard night… Readd
missing action action-purchase-order-method-fill-company-bank-details
which was dropped then. The diff is to ugly for me to dig into to see if
more stuff was accidentaly dropped. I guess a git training won't hurt
=> purchases: fix order company bank details

axelor-base/src/main/java/com/axelor/apps/base/service/tax/FiscalPositionServiceImpl.java, axelor-purchase/src/main/java/com/axelor/apps/purchase/web/PurchaseOrderLineController.java, axelor-purchase/src/main/resources/views/PurchaseOrderLine.xml, axelor-sale/src/main/java/com/axelor/apps/sale/web/SaleOrderLineController.java, axelor-sale/src/main/resources/views/SaleOrderLine.xml
taxEquiv was only set when product was selected, making it inconsistent
in case of tax change. This was also preventing the popup to close
because of invalid taxEquiv field if taxLine was cleared.
=> sale/purchase: correctly update taxEquiv on taxLine change

axelor-human-resource/src/main/resources/reports/Expense.rptdesign
All translated fields were checking row['message_key'] != "" whereas
its value is null when no translation is present. This was causing
missing elements in the report, especially the "kilometric allow param",
when in foreign language (eg. french).
Moreover fix a typo in Kilometric Allowance preventing the title to be
properly printed on report.
The kilometric_allow_param can be translated in the report which is
strange since these are user defined strings, but leave it this way as
changing it might trigger https://xkcd.com/1172/
=> expense: fix translation handling

axelor-base/src/main/java/com/axelor/apps/base/service/imports/listener/ImporterListener.java
When multiple files were imported at the same time, success & total were
only taking the last file into account.
=> import: fix wrong records count on multiple files

axelor-base/src/main/resources/views/Partner.xml, axelor-crm/src/main/resources/views/Lead.xml, axelor-human-resource/src/main/resources/views/Employee.xml
Regex wasn't allowing two parts websites (http://xxx.yy), improve it by
forcing http:// prefix and leveraging overall check.
=> partner/lead/employee: improve website regex

CHANGELOG.md, axelor-account/src/main/resources/views/Account.xml
Addendum to commit 22d3e31, use partner name as default name for created
account.
=> account: slightly improve account creation from partner

CHANGELOG.md, axelor-account/src/main/java/com/axelor/apps/account/service/AccountManagementServiceAccountImpl.java, axelor-base/src/main/java/com/axelor/apps/base/service/tax/AccountManagementServiceImpl.java, axelor-base/src/main/java/com/axelor/apps/base/service/tax/TaxService.java, axelor-base/src/main/resources/domains/TaxEquiv.xml, axelor-base/src/main/resources/views/TaxEquiv.xml
Standard accounting rules for intra-EU VAT is as follow in France (for a standard rate VAT):
- French VAT account is replaced by intra-EU VAT account;
- Reverse charging is done on the opposite intra-EU VAT account.
For a purchase invoice it gives:
- 4456xx is replaced by 445662
- reverse charge is done on 4452xx
So we've to be able to both replace and reverse charge at the same time.
=> account: allow both substitution and reverseCharge on TaxEquiv

CHANGELOG.md, axelor-account/src/main/resources/views/PaymentVoucher.xml
Button was hidden for supplier payments when it shouldn't
=> PaymentVoucher: fix display of confirm button for credit card payments

axelor-account/src/main/resources/views/FixedAssetCategory.xml
As its name implies, the account should be of type "charge" not "immobilisation" (sic).
Moreover this fixes an inconsistency between demo data and filter.
=> Fixed asset: fix domain of chargeAccount

axelor-contract/src/main/resources/i18n/messages_fr.csv
It was overriding the axelor-account module one with a typo.
=> i18n: remove wrong fiscal position translation

axelor-account/src/main/java/com/axelor/apps/account/service/FixedAssetServiceImpl.java
Do not check whether config flag fixedAssetCatReqOnInvoice is set to
create the fixed asset. If user filled the category it is likely that he
wants to create the asset. Moreover the label of the option does not
indicate in any way that setting it to false will prevent any automatic
fixed asset creation.
=> fixedAssets: create from invoice when category is filled

axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/service/batch/BatchDirectDebitCustomerInvoice.java
"Create bank order" button on the batch form should only be shown when
there is no bank order generated from the batch.
=> Link batch to generated bank order

CHANGELOG.md, axelor-account/build.gradle, axelor-account/src/main/java/com/axelor/apps/account/service/payment/PayboxService.java, axelor-bank-payment/build.gradle, axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/ebics/certificate/KeyStoreManager.java, axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/ebics/certificate/X509Generator.java, axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/ebics/service/EbicsCertificateService.java, axelor-base/build.gradle, axelor-studio/build.gradle
Upgrade Bouncy Castle dependencies in order to consistently use
"bcprov-jdk15on" and "bcpkix-jdk15on" modules.
Addresses RM-19229
=> Upgrade Bouncy Castle dependencies

CHANGELOG.md, axelor-base/src/main/java/com/axelor/apps/base/service/message/TemplateMessageServiceBaseImpl.java, axelor-message/src/main/java/com/axelor/apps/message/service/MessageServiceImpl.java
Use JPA.flush() in order to make sure the message can be found in the
email sending thread.
Also generate report only after adding all parameters.
Addresses RM-19679
=> Fix random NPE when sending emails asynchronously

CHANGELOG.md, axelor-stock/src/main/java/com/axelor/apps/stock/service/StockMoveLineService.java, axelor-stock/src/main/java/com/axelor/apps/stock/service/StockMoveLineServiceImpl.java, axelor-stock/src/main/java/com/axelor/apps/stock/service/StockMoveServiceImpl.java, axelor-stock/src/main/resources/domains/StockMoveLine.xml, axelor-stock/src/main/resources/i18n/messages.csv, axelor-stock/src/main/resources/i18n/messages_en.csv, axelor-stock/src/main/resources/i18n/messages_fr.csv, axelor-stock/src/main/resources/views/StockMove.xml, axelor-stock/src/main/resources/views/StockMoveLine.xml
Customer returns now have a new field that will be used to manage
weighted average price. This field contains the wap at the time of
realization of the customer delivery. Previously the price from customer
delivery was used for average price.
=> RM20753: fix WAP computation on customer returns.

axelor-project/src/main/resources/views/TeamTask.xml
product, quantity, unit, unitPrice, currency and exTaxTotal fields should not be reset on change of invoicingType
=> [Anomaly #21675] TEAMTASKS : financial data - update

CHANGELOG.md, axelor-base/src/main/java/com/axelor/apps/base/db/repo/UserBaseRepository.java
AOS doesn't use user email field, so finder methods in user repository
need to be overridden.
This is needed when finding user by email address via single sign-on.
Addresses RM-19444
=> Find user by email using partner email address

CHANGELOG.md, axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/service/bankorder/BankOrderMoveServiceImpl.java, axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/service/bankorder/BankOrderServiceImpl.java, axelor-human-resource/src/main/java/com/axelor/apps/hr/service/bankorder/BankOrderServiceHRImpl.java
BANK ORDER : corrected the possibility to generate two times the same move and corrected the behavior of bank order, now the bank order moves can be generated on validation or realization.
=> RM#23948: cherry-pick from 5.1 

CHANGELOG.md, axelor-account/src/main/resources/views/MoveLine.xml
When debit/credit is filled the other field is set to 0 instead of being set to a readonly mode
=> RM26407 change UI for debit/credit fields

CHANGELOG.md, axelor-account/src/main/java/com/axelor/apps/account/service/invoice/generator/tax/TaxInvoiceLine.java
An invoice tax line generated from a reverse charge tax was considered
as fixed asset during invoice ventilation because some fields were not
correctly filled.
Refactored whole class to be easier to understand and maintain. The
refactoring fixes the issue.
Fixes RM27987
=> Fix reverse charge invoice tax line as fixed asset

axelor-stock/src/main/resources/views/StockMoveLine.xml, axelor-supplychain/src/main/resources/views/StockMoveLine.xml, changelogs/unreleased/stock-move-line-fix-price-not-coherent.yml
The price is readonly if the line is linked to an order. Else on
changing the price we update other price fields.
Fixes RM27237.
=> Stock Move Line: Fix prices not being coherent

axelor-sale/src/main/resources/reports/SaleOrder.rptdesign, changelogs/unreleased/fix-qty-sale-order-report.yml
Regardless of the sale order line type, the column qty/unit is always displayed
=> Anomaly RM#35892: Sale order report: qty column is displayed

axelor-base/src/main/java/com/axelor/apps/base/service/administration/SequenceService.java, changelogs/unreleased/fix-sequence-incrementing-on-exception.yml
Instead of using a separate thread for incrementing sequence, we use a
database lock so any thread will wait for a given sequence to be
available before modifying it.
RM45139
=> Sequence: fix increment on exception

axelor-production/src/main/java/com/axelor/apps/production/service/MrpServiceProductionImpl.java, changelogs/unreleased/fix-npe-mrp-computation.yml
NPE occured when having multiple BOM level: intermediate levels are not
added to the productMap, and cause a NPE later.
RM24332
=> MRP: fix NPE during computation

axelor-business-production/src/main/java/com/axelor/apps/businessproduction/service/ProductionOrderServiceBusinessImpl.java, axelor-production/src/main/java/com/axelor/apps/production/service/MrpLineServiceProductionImpl.java, axelor-production/src/main/java/com/axelor/apps/production/service/manuforder/ManufOrderService.java, axelor-production/src/main/java/com/axelor/apps/production/service/manuforder/ManufOrderServiceImpl.java, axelor-production/src/main/java/com/axelor/apps/production/service/productionorder/ProductionOrderSaleOrderServiceImpl.java, axelor-production/src/main/java/com/axelor/apps/production/service/productionorder/ProductionOrderService.java, axelor-production/src/main/java/com/axelor/apps/production/service/productionorder/ProductionOrderServiceImpl.java, axelor-production/src/main/java/com/axelor/apps/production/web/ProductionOrderController.java
Signed-off-by: David Trochel <d.trochel@axelor.com>
=> RM47537 Use enum instead of int consts for ManufOrder originType

axelor-account/src/main/java/com/axelor/apps/account/service/ReconcileServiceImpl.java, axelor-account/src/main/java/com/axelor/apps/account/service/move/MoveReverseServiceImpl.java, axelor-account/src/main/resources/domains/Invoice.xml
- When reconciling and generating invoice payment, to find the related
invoice we do not find the invoice in the move, but instead we fetch
the invoice linking to the move.
- Do not copy the link to invoice and payment voucher when reversing a
move.
RM45877
=> Invoice: fix double payment created when reversing move

axelor-stock/src/main/resources/views/StockLocation.xml, changelogs/unreleased/47871-fix-print-grid-stock-location.yml
Anomaly RM#47871: Corrected print button not working on StockLocation grid view by removing useless save action
=> Anomaly #47871: StockLocation grid view print button does not work

axelor-sale/src/main/resources/demo/en/base_template.csv, axelor-sale/src/main/resources/demo/fr/base_template.csv, changelogs/unreleased/add-unit-on-sale-order-template.yml
* Anomaly RM#49766: TEMPLATE : missing unit on sale order template
* Update add-unit-on-sale-order-template.yml
Co-authored-by: gdu-axelor <g.dubaux@axelor.com>
=> Anomaly RM#49766: TEMPLATE : missing unit on sale order template (#8204)

axelor-account/src/main/java/com/axelor/apps/account/service/move/MoveToolService.java, axelor-account/src/main/java/com/axelor/apps/account/service/move/MoveToolServiceImpl.java, axelor-account/src/main/java/com/axelor/apps/account/service/payment/invoice/payment/InvoicePaymentValidateServiceImpl.java, axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/service/invoice/payment/InvoicePaymentValidateServiceBankPayImpl.java
It was previously impossible to pay an advance payment invoice due to 6.4 changes. This commit correctly manages the case where an invoice payment is missing a move from the invoice.
RM52775
=> Invoice: fixed advance payment on invoice

axelor-account/src/main/java/com/axelor/apps/account/service/move/record/MoveDefaultServiceImpl.java, axelor-account/src/main/resources/views/Move.xml, changelogs/unreleased/63864.yaml
Replaced on field 'currency' in 'onChange' attribute "action-move-record-set-currency-code" by "action-move-method-set-default-move-currency". Modify 'setDefaultCurrency' in 'MoveDefaultServiceImpl' by adding 'move.getPartner() == null' in if condition, so now when a company is chosen and a partner exist, we don't override the partner currency by the company currency.
=> RM#63864 Replaced deleted action by existing one

axelor-account/src/main/java/com/axelor/apps/account/service/move/MoveViewHelperServiceImpl.java, changelogs/unreleased/64108.yaml
When creating an account move, when you select a partner and filter the partners by the company, we check that the company is not null. Added a condition in filterPartner method in MoveViewHelperServiceImpl.
=> RM#64108 Correct NPE when selecting partner and Company is empty

axelor-crm/src/main/resources/views/Lead.xml
In lead, when clicking on status equal to appCRM.convertedLeadStatus, call same process as convert button.
=> RM#65837 Fix on conversion on statusSelect CRM 7.1

axelor-base/src/main/resources/views/MetaMenu.xml
Field "top" does not exist anymore in meta menu, as it was removed in AOP v7.
RM71265
=> Remove warning when reloading view

axelor-sale/src/main/java/com/axelor/apps/sale/service/saleorder/SaleOrderLineServiceImpl.java, changelogs/unreleased/64349.yaml
If a product has field 'expense' as null product can still be selectable in a sale order line. We did it by adding a clause in the domain 'OR self.expense IS NULL'.
=> RM#64349 Some products are now selectable in sale order line

axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/SaleOrderInvoiceServiceImpl.java, changelogs/unreleased/75696-fix-delivery-address-on-advance-payment-invoice-printings.yml
During the generation of advance payment invoice from a sale order, deliveryAddressStr is now filled.
RM75696
=> Invoice: fill deliveryAddressStr on advance payment invoice
