- axelor-account/src/main/resources/views/Dashboard.xml
- axelor-account/src/main/resources/views/Invoice.xml
- axelor-account/src/main/resources/views/Menu.xml
Added a gridview (invoice-supplier-grid) specific to suppliers invoices, in order to display external reference
> #5319 : Added externalRef in GridView for suppliers invoices

- axelor-production/src/main/java/com/axelor/apps/production/service/CostSheetServiceImpl.java
- axelor-production/src/main/java/com/axelor/apps/production/service/OperationOrderWorkflowService.java
- axelor-production/src/main/resources/domains/ProdProcessLine.xml
- axelor-production/src/main/resources/domains/WorkCenter.xml
- axelor-production/src/main/resources/views/ProdProcessLine.xml
- axelor-production/src/main/resources/views/WorkCenter.xml
Change capacityPerCyle by minCapacityPerCycle in domain, view, java, ...
> #5177 Change capacityPerCyle by minCapacityPerCycle

- axelor-human-resource/src/main/resources/domains/Expense.xml
- axelor-human-resource/src/main/resources/views/Expense.xml
- axelor-human-resource/src/main/resources/views/Timesheet.xml
It works on Timesheet but not in Expenses.
> #5631 HR Add x-can-copy on timesheetList and ExpensesList

- axelor-account/src/main/resources/views/Account.xml
- axelor-account/src/main/resources/views/Menu.xml
Open account details on double click (only on Chart of account)
> #5737 Account Open account details 

- axelor-base/src/main/resources/views/PriceListLine.xml
- axelor-base/src/main/resources/views/Selects.xml
- axelor-demo-en/src/main/resources/data-demo/input/base_printSetting.csv
- axelor-demo-fr/src/main/resources/data-demo/input/base_printSetting.csv
The values imported from csv files were modified by html fields when the
view was called. The imported values are changed to fix this.
> RM7096 : changed demo values

- axelor-account/src/main/java/com/axelor/apps/account/service/payment/paymentvoucher/PaymentVoucherLoadService.java
- axelor-account/src/main/java/com/axelor/apps/account/web/PayVoucherElementController.java
- axelor-account/src/main/resources/i18n/messages_fr.csv
- axelor-account/src/main/resources/views/PayVoucherElementToPay.xml
- axelor-account/src/main/resources/views/PaymentVoucher.xml
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/lunch/voucher/LunchVoucherMgtLineService.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/lunch/voucher/LunchVoucherMgtLineServiceImpl.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/lunch/voucher/LunchVoucherMgtServiceImpl.java
- axelor-human-resource/src/main/resources/domains/LunchVoucherMgtLine.xml
- axelor-human-resource/src/main/resources/views/LunchVoucherMgt.xml
- axelor-human-resource/src/main/resources/views/LunchVoucherMgtLine.xml
- axelor-human-resource/src/main/resources/views/Selects.xml
Added a status for lunch voucher line. If an exception occurs during the
line creation, the status is set to 'Anomaly'. Using the button
"Calculate" allow the user to redo the operation on lines with anomaly.
> RM6947: anomaly management for Lunch Voucher Line

- axelor-account/src/main/resources/reports/Invoice.rptdesign
- axelor-base/src/main/resources/reports/MessagePDF.rptdesign
- axelor-base/src/main/resources/reports/ProductCatalog_PGQL.rptdesign
- axelor-crm/src/main/resources/reports/Lead.rptdesign
- axelor-production/src/main/resources/reports/ManufOrder.rptdesign
- axelor-production/src/main/resources/reports/OperationOrder.rptdesign
- axelor-purchase/src/main/resources/reports/PurchaseOrder.rptdesign
- axelor-stock/src/main/resources/reports/StockLocation.rptdesign
- axelor-stock/src/main/resources/reports/StockMove.rptdesign
- In some birt reports, deleted post request filters and added a dynamic WHERE
clause to improve performances.
- Fixed a bug in invoice report. Now, on printing multiple invoices, the
contact name is the correct one for each invoice.
> Added dynamic SQL requests + bug fix in reports

- axelor-account/src/main/java/com/axelor/apps/account/service/MoveLineExportService.java
- axelor-account/src/main/resources/reports/Invoice.rptdesign
- axelor-business-project/src/main/resources/reports/InvoiceAnnex.rptdesign
- axelor-purchase/src/main/resources/reports/PurchaseOrder.rptdesign
Added a dynamic WHERE clause instead of a birt filter for optimization.
Also fixed a typo when creating the headers for FEC export.
> Fixed Invoice and InvoiceAnnex reports

- axelor-account/src/main/resources/views/Invoice.xml
- axelor-bank-payment/src/main/resources/views/BankOrder.xml
- axelor-base/src/main/resources/views/Blocking.xml
- axelor-project/src/main/resources/views/ProjectTask.xml
Some action-attrs were trying to set domain without correctly checking
if the used variables were null or empty. Fixed this by adding a
condition on the action.
> RM7195: fixed action-attrs setting domain in views

- axelor-human-resource/src/main/resources/views/Employee.xml
> Implement feature #7312.

- axelor-human-resource/src/main/resources/views/Charts.xml
- axelor-human-resource/src/main/resources/views/Timesheet.xml
- Merge the two charts into one. Put it under the timesheet lines.
- Move validation and refusal information to the side.
Show each field if it is not null.
> Implement feature #7313.

- axelor-production/src/main/resources/views/BillOfMaterial.xml
BillOfMaterial: display the field "Label" in bold and bigger in read-only
mode.
> Implement feature #7309.

- axelor-base/src/main/java/com/axelor/apps/base/service/administration/GeneralServiceImpl.java
- axelor-base/src/main/java/com/axelor/apps/base/web/GeneralController.java
- axelor-base/src/main/java/com/axelor/apps/base/web/UserController.java
- axelor-base/src/main/resources/views/General.xml
- axelor-base/src/main/resources/views/User.xml
Default to hidden date fields in General and User, and unhide them if
application.mode = dev.
> Feature #7006

- axelor-project/src/main/resources/views/Project.xml
> #7364 fixed duplicate view on action view project task tree

- axelor-base/src/main/java/com/axelor/apps/base/exceptions/IExceptionMessage.java
- axelor-base/src/main/java/com/axelor/apps/base/service/PartnerService.java
- axelor-base/src/main/java/com/axelor/apps/base/web/PartnerController.java
- axelor-base/src/main/resources/domains/Partner.xml
- axelor-base/src/main/resources/views/Partner.xml
Add a button to convert a contact partner into an individual partner.
> Feature #7168

- axelor-bank-payment/src/main/resources/domains/BankOrder.xml
- axelor-bank-payment/src/main/resources/i18n/messages.csv
- axelor-bank-payment/src/main/resources/i18n/messages_en.csv
- axelor-bank-payment/src/main/resources/i18n/messages_fr.csv
- axelor-bank-payment/src/main/resources/views/BankOrder.xml
+ bank order date became bank order due date
+ hilite danger when the date is near (2 days) or overdue
+ hilite warning if the order is not realized yet
+ field confirmation date is shown in grid view.
> RM7374: Changes in bank order view

- axelor-base/src/main/resources/views/Product.xml
Fix productSubTypeSelect in the view.
> Anomaly #7385

- axelor-base/src/main/resources/views/Product.xml
Fix domains for weightUnit and lengthUnit.
> Anomaly #7389

- axelor-demo-en/src/main/resources/data-demo/input/stock_location.csv
- axelor-demo-fr/src/main/resources/data-demo/input/stock_location.csv
- axelor-stock/src/main/resources/data-init/input/stock_location.csv
- axelor-stock/src/main/resources/views/Menu.xml
Changed in data init and demo data the type of location for supplier and
customer. Also fixed menu entry so they display virtual locations.
> RM7433: Location imports external → virtual

- axelor-account/src/main/resources/views/Partner.xml
Creation or update of bank details from Partner now updates ibanbic as
well.
> RM7425: BankDetails update from Partner fix

- axelor-supplychain/src/main/java/com/axelor/csv/script/ValidateSupplyChain.java
> Anomaly #7505

- axelor-stock/src/main/java/com/axelor/apps/stock/service/InventoryService.java
- axelor-stock/src/main/java/com/axelor/apps/stock/service/StockMoveService.java
- axelor-stock/src/main/java/com/axelor/apps/stock/service/StockMoveServiceImpl.java
- axelor-supplychain/src/main/java/com/axelor/csv/script/ValidateSupplyChain.java
Fix inventory validation that wasn't able to generate a stock move.
> Anomaly #7437

- axelor-stock/src/main/java/com/axelor/apps/stock/service/LocationService.java
- axelor-stock/src/main/java/com/axelor/apps/stock/service/LocationServiceImpl.java
- axelor-stock/src/main/java/com/axelor/apps/stock/service/StockMoveLineServiceImpl.java
- axelor-stock/src/main/resources/views/Product.xml
avgPrice in Product is updated at every stock move, no longer in the
view.
> Product : AvgPrice in stock updates improvement

- axelor-human-resource/src/main/java/com/axelor/apps/hr/web/expense/ExpenseController.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/web/leave/LeaveController.java
- axelor-human-resource/src/main/resources/views/Expense.xml
- axelor-human-resource/src/main/resources/views/ExtraHours.xml
- axelor-human-resource/src/main/resources/views/LeaveRequest.xml
- axelor-human-resource/src/main/resources/views/Timesheet.xml
Human resources: close wizard for Complete my timesheet, expense, and leave request.
> Feature #7516

- axelor-stock/src/main/resources/demo/en/stock_stockRules.csv
- axelor-stock/src/main/resources/demo/fr/stock_stockRules.csv
> Feature #6111

- axelor-human-resource/src/main/resources/views/Expense.xml
Readonly fields when expense is ventilated.
> Anomaly #7743: EXPENSE : ventilate

- axelor-human-resource/src/main/resources/views/Expense.xml
Don't show payment if it is not registered.
> Anomaly #7741: EXPENSE : total

- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/batch/BatchLeaveManagementReset.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/batch/HrBatchService.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/leave/management/LeaveManagementService.java
- axelor-human-resource/src/main/resources/domains/HRBatch.xml
- axelor-human-resource/src/main/resources/i18n/messages.csv
- axelor-human-resource/src/main/resources/i18n/messages_en.csv
- axelor-human-resource/src/main/resources/i18n/messages_fr.csv
- axelor-human-resource/src/main/resources/views/HRBatch.xml
- axelor-human-resource/src/main/resources/views/Selects.xml
HR BATCH : reset to zero the leave reason counters
> Feature #7782

- axelor-base/src/main/resources/domains/Product.xml
- axelor-base/src/main/resources/i18n/messages.csv
- axelor-base/src/main/resources/i18n/messages_en.csv
- axelor-base/src/main/resources/i18n/messages_fr.csv
- axelor-base/src/main/resources/views/Product.xml
- axelor-sale/src/main/java/com/axelor/apps/sale/service/SaleOrderServiceImpl.java
- axelor-stock/src/main/java/com/axelor/apps/stock/exception/IExceptionMessage.java
- axelor-stock/src/main/java/com/axelor/apps/stock/service/StockMoveLineService.java
- axelor-stock/src/main/java/com/axelor/apps/stock/service/StockMoveLineServiceImpl.java
- axelor-stock/src/main/java/com/axelor/apps/stock/service/StockMoveServiceImpl.java
Check for expiration dates when realizing a stock move.
> Feature #5032

- axelor-account/src/main/java/com/axelor/apps/account/service/invoice/InvoiceService.java
- axelor-account/src/main/java/com/axelor/apps/account/service/invoice/InvoiceServiceImpl.java
- axelor-account/src/main/java/com/axelor/apps/account/web/InvoiceController.java
- axelor-account/src/main/resources/views/Invoice.xml
- axelor-purchase/src/main/java/com/axelor/apps/purchase/service/PurchaseOrderService.java
- axelor-purchase/src/main/java/com/axelor/apps/purchase/service/PurchaseOrderServiceImpl.java
- axelor-purchase/src/main/java/com/axelor/apps/purchase/web/PurchaseOrderController.java
- axelor-purchase/src/main/resources/views/PurchaseOrder.xml
- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/PurchaseOrderInvoiceServiceImpl.java
- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/PurchaseOrderServiceSupplychainImpl.java
Rollbackable purchase order validation
Rollbackable invoice validation
> Anomaly #7763

- axelor-account/src/main/java/com/axelor/apps/account/service/payment/PaymentModeServiceImpl.java
Fix NPE when there is no cash account configured.
> Anomaly #7825

- axelor-sale/src/main/java/com/axelor/apps/sale/service/ConfiguratorCreatorServiceImpl.java
- axelor-sale/src/main/java/com/axelor/apps/sale/service/ConfiguratorServiceImpl.java
- axelor-sale/src/main/resources/views/SaleOrder.xml
+ Change indicators name field to be unique per configurator creator.
+ Hide generator button in sale order when the status is not draft.
> Fix in configurator: indicator fields button

- axelor-production/src/main/java/com/axelor/apps/production/service/ManufOrderWorkflowService.java
- axelor-production/src/main/java/com/axelor/apps/production/service/MrpServiceProductionImpl.java
- axelor-production/src/main/java/com/axelor/apps/production/service/OperationOrderWorkflowService.java
- axelor-production/src/main/java/com/axelor/apps/production/web/ManufOrderController.java
- axelor-production/src/main/resources/domains/ManufOrder.xml
- axelor-production/src/main/resources/views/ManufOrder.xml
Manufacturing order - problem when you change planned dates
> Anomaly #7837

- axelor-production/src/main/java/com/axelor/apps/production/service/OperationOrderWorkflowService.java
- axelor-production/src/main/java/com/axelor/apps/production/web/OperationOrderController.java
- axelor-production/src/main/resources/views/OperationOrder.xml
Manufacturing - planned operations calendar
> Anomaly #7838

- axelor-account/src/main/java/com/axelor/apps/account/web/AccountingSituationController.java
- axelor-purchase/src/main/java/com/axelor/apps/purchase/exception/IExceptionMessage.java
- axelor-purchase/src/main/java/com/axelor/apps/purchase/service/PurchaseOrderLineService.java
- axelor-purchase/src/main/java/com/axelor/apps/purchase/service/PurchaseOrderLineServiceImpl.java
- axelor-purchase/src/main/java/com/axelor/apps/purchase/web/PurchaseOrderLineController.java
- axelor-purchase/src/main/resources/i18n/messages.csv
- axelor-purchase/src/main/resources/i18n/messages_en.csv
- axelor-purchase/src/main/resources/i18n/messages_fr.csv
- axelor-purchase/src/main/resources/views/PurchaseOrderLine.xml
PURCHASEORDERLINE : min quantity and unit price
> Feature #7836

- axelor-crm/src/main/java/com/axelor/apps/crm/web/ConvertLeadWizardController.java
- axelor-crm/src/main/resources/views/ConvertLeadWizard.xml
CONVERT LEAD : close the current page
> Feature #5991

- axelor-stock/src/main/java/com/axelor/apps/stock/service/StockMoveLineService.java
- axelor-stock/src/main/java/com/axelor/apps/stock/service/StockMoveLineServiceImpl.java
- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/StockMoveInvoiceServiceImpl.java
- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/invoice/generator/InvoiceLineGeneratorSupplyChain.java
INVOICE : Stock move with tracking number
> Feature #4742

- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/invoice/generator/InvoiceLineGeneratorSupplyChain.java
NPE when generating an invoice from a stock move
> Anomaly #7906

- axelor-account/src/main/resources/domains/PayerQualityConfigLine.xml
- axelor-account/src/main/resources/views/PayerQualityConfigLine.xml
> Anomaly #7855

- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/KilometricService.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/web/expense/ExpenseController.java
- axelor-human-resource/src/main/resources/domains/ExpenseLine.xml
- axelor-human-resource/src/main/resources/views/ExpenseLine.xml
Remove action-kilometric-allowance-record-in-tax-total.
Add getDistanceTravelled.
> Rework kilometric allowance.

- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/KilometricService.java
- axelor-human-resource/src/main/resources/domains/AppExpense.xml
- axelor-human-resource/src/main/resources/i18n/messages.csv
- axelor-human-resource/src/main/resources/i18n/messages_en.csv
- axelor-human-resource/src/main/resources/i18n/messages_fr.csv
- axelor-human-resource/src/main/resources/views/AppExpense.xml
> Retrieve Google Maps API key from AppBase.

- axelor-production/src/main/resources/views/ProductionOrderWizard.xml
> Fix invalid datetime field in production order wizard form.

- axelor-sale/src/main/java/com/axelor/apps/sale/service/ConfiguratorService.java
- axelor-sale/src/main/java/com/axelor/apps/sale/service/ConfiguratorServiceImpl.java
- axelor-sale/src/main/java/com/axelor/apps/sale/web/ConfiguratorController.java
- axelor-sale/src/main/resources/domains/ConfiguratorFormula.xml
- axelor-sale/src/main/resources/views/Configurator.xml
- axelor-sale/src/main/resources/views/ConfiguratorCreator.xml
- axelor-sale/src/main/resources/views/ConfiguratorFormula.xml
Adapted the services to this change. Fixed many to one bug for sale
order line generation.
> RM8432: move updateFromSelect configurator→formula

- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/web/SaleOrderController.java
* Optimize code.
* Use TraceBackService to catch exception.
> Fix anomaly #4724: Catch exception in TraceBack

- axelor-base/src/main/java/com/axelor/apps/base/web/PartnerController.java
- axelor-base/src/main/resources/views/Partner.xml
- axelor-crm/src/main/java/com/axelor/apps/crm/web/LeadController.java
- axelor-crm/src/main/resources/views/Lead.xml
* Add function for check if name of partner or lead already exists.
> Fix feature #7591: Check partner/lead name

- axelor-account/src/main/resources/views/AccountConfig.xml
- axelor-account/src/main/resources/views/AccountingSituation.xml
- axelor-account/src/main/resources/views/Invoice.xml
* Apply filter on the field invoiceAutomaticMail in Invoice for take
only model with tableName equal to 'ACCOUNT_INVOICE' in metaModel.
> RM#8672: Apply filter on invoiceAutomaticMail

- axelor-sale/src/main/java/com/axelor/apps/sale/service/SaleOrderServiceImpl.java
* Fix missing use of method params in createSaleOrder. deliveryDate and team are not set.
> RM#8699: Fix createSaleOrder method

- axelor-sale/src/main/java/com/axelor/apps/sale/service/SaleOrderLineServiceImpl.java
* Fix bug of reset when productName is fill and not productCode.
> RM#8737: Fix reset of SaleOrderLine

- axelor-human-resource/src/main/resources/views/HRConfig.xml
Reverts axelor/axelor-business-suite#724
> Revert "Anomaly #8876: add a canNew=true in kilometricAllowanceRateList view"

- axelor-account/src/main/java/com/axelor/apps/account/web/InvoiceController.java
- axelor-purchase/src/main/resources/views/PurchaseOrder.xml
* Fix context filling from PurchaseOrder to Invoice form.
> RM#8932: Fix NPE Invoice from PurchaseOrder

- axelor-crm/src/main/resources/views/Partner.xml
* Add context in action-partner-view-create-opportunity for fix missing variable in Opportunity form.
> RM#8928: Fix JS error in Opportunity

- axelor-account/src/main/java/com/axelor/apps/account/service/debtrecovery/ReminderActionService.java
- axelor-account/src/main/java/com/axelor/apps/account/service/debtrecovery/ReminderService.java
Avoid NPE and correctly set bidirectionnal relationship
> RM8982: Fix reminder batch

- axelor-account/src/main/java/com/axelor/apps/account/web/PaymentVoucherController.java
- axelor-account/src/main/resources/i18n/messages_fr.csv
- axelor-account/src/main/resources/views/PaymentVoucher.xml
- axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/service/bankorder/BankOrderServiceImpl.java
- axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/web/BankOrderController.java
- axelor-bank-payment/src/main/resources/domains/BankOrder.xml
- axelor-bank-payment/src/main/resources/i18n/messages_fr.csv
- axelor-bank-payment/src/main/resources/views/BankOrder.xml
- axelor-bank-payment/src/main/resources/views/Menu.xml
* Show autoImput if autoReconcileOnPayment is check.
* Ask for continue generation payment if excessPaymentOk and autoImput is check.
* Hide fields not neccessary for payment if autoImput is checked.
* Change french translate of Auto Input field.
> Fix feature #8162 : Excess payment

- axelor-sale/src/main/resources/domains/SaleOrderLine.xml
- axelor-sale/src/main/resources/views/SaleOrder.xml
- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/SaleOrderStockService.java
- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/SaleOrderStockServiceImpl.java
- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/web/SaleOrderController.java
- axelor-supplychain/src/main/resources/domains/StockMoveLine.xml
- axelor-supplychain/src/main/resources/views/SaleOrder.xml
* Add in SaleOrder's form, a span for indicated if all or partial stock
move line are shipped.
> RM#9036: Add StockMove line delivery status

- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/KilometricService.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/batch/BatchLeaveManagement.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/expense/ExpenseService.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/expense/ExpenseServiceImpl.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/leave/LeaveServiceImpl.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/timesheet/TimesheetServiceImpl.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/web/expense/ExpenseController.java
- axelor-human-resource/src/main/resources/views/Timesheet.xml
Also added small fixes / refactor in code
> RM9254: use pay instead of active company in HR

- axelor-account/src/main/java/com/axelor/apps/account/service/batch/BatchDebtRecovery.java
* Fetch only customer partner.
> RM#9515: add additional filter in BatchDebtRecovery

- axelor-account/src/main/java/com/axelor/apps/account/service/invoice/generator/InvoiceGenerator.java
add/remove/clear methods not working on proxy objects.
> RM9759: workaround

- axelor-base/src/main/resources/views/User.xml
- axelor-human-resource/src/main/resources/views/EmployeeAdvance.xml
- axelor-human-resource/src/main/resources/views/EmployeeBonusMgtLine.xml
- axelor-human-resource/src/main/resources/views/EmploymentContract.xml
- axelor-human-resource/src/main/resources/views/LunchVoucherAdvance.xml
- axelor-human-resource/src/main/resources/views/LunchVoucherMgtLine.xml
- axelor-human-resource/src/main/resources/views/PayrollPreparation.xml
- axelor-production/src/main/resources/views/ProdHumanResource.xml
We can only have a complete access to it through its menu entry in 'Administration'.
> RM9803: prevent creation, edit and view of object employee.

- axelor-bank-payment/src/main/resources/views/EbicsUser.xml
Reverts axelor/axelor-business-suite#1173
> Revert "RM9780: Display assciated user only when user type is "Signatory"."

- axelor-account/src/main/java/com/axelor/apps/account/module/AccountModule.java
- axelor-account/src/main/java/com/axelor/apps/account/service/invoice/InvoiceLineService.java
- axelor-account/src/main/java/com/axelor/apps/account/service/invoice/InvoiceLineServiceImpl.java
- axelor-account/src/main/java/com/axelor/apps/account/web/InvoiceLineController.java
- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/module/SupplychainModule.java
- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/InvoiceLineSupplychainService.java
* Rename InvoiceLineService to InvoiceLineServiceImpl
* Add InvoiceLineService interface with InvoiceLineServiceImpl method prototype
* Refactor getProductInformation with resetProductInformation and fillProductInformation from InvoiceLineService.
> InvoiceLineService refactor and update getProductInformation method

- axelor-account/src/main/java/com/axelor/apps/account/web/InvoiceController.java
- axelor-base/src/main/resources/views/Company.xml
- axelor-purchase/src/main/java/com/axelor/apps/purchase/web/PurchaseOrderController.java
- axelor-sale/src/main/java/com/axelor/apps/sale/web/SaleOrderController.java
- axelor-stock/src/main/java/com/axelor/apps/stock/web/StockMoveController.java
Also fixed printing settings domain in invoice, sale order, purchase
order, stock move form
> RM10159: company printing settings required

- axelor-prestashop/src/main/java/com/axelor/apps/prestashop/exports/service/ExportProductServiceImpl.java
Field renaming wasn't propagated to Prestashop module causing query to throw exception
> prestashop: fix fromLocation/toLocation typo

- axelor-production/src/main/java/com/axelor/apps/production/service/ManufOrderServiceImpl.java
- axelor-production/src/main/java/com/axelor/apps/production/service/ManufOrderStockMoveService.java
- axelor-production/src/main/java/com/axelor/apps/production/service/OperationOrderStockMoveService.java
- axelor-stock/src/main/java/com/axelor/apps/stock/service/InventoryService.java
- axelor-stock/src/main/java/com/axelor/apps/stock/service/StockMoveLineServiceImpl.java
- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/SaleOrderStockServiceImpl.java
StockMoveLineService::createStockMoveLine already adds the created stock
move line to the stock move.
> RM10917: fix duplicate stock move lines.

- axelor-sale/src/main/resources/domains/SaleOrder.xml
Since lines have an attribute to order them, use it on entity's getter
> SaleOrder: add orderBy for lines

- axelor-base/src/main/resources/views/Product.xml
A typo prevents unit selection in product form
> Product unit cannot be set

- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/SaleOrderInvoiceService.java
- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/SaleOrderInvoiceServiceImpl.java
needed for axelor/axelor-addons#7
> supplychain: add method to get an order invoices

- axelor-sale/src/main/java/com/axelor/apps/sale/service/saleorder/SaleOrderCreateService.java
needed for axelor/axelor-addons#7
> sales: add documentation on createSaleOrder service method

- axelor-account/src/main/java/com/axelor/apps/account/service/AccountingSituationService.java
- axelor-account/src/main/java/com/axelor/apps/account/service/AccountingSituationServiceImpl.java
This handle defaulting to company one if needed (needed for axelor/axelor-addons#7)
> account: add method to get CompanyBankDetails from Partner

- axelor-account/src/main/resources/reports/Invoice.rptdesign
Honor the clientBox parameter existing in accounting configuration.
Displays is the same as for sale orders
> invoice: show client box on sales invoices

- axelor-crm/src/main/resources/domains/Lead.xml
Reverts axelor/axelor-business-suite#1698
> Revert "Anomaly #11725 LEAD : Issue with namecolumn of lead"

- axelor-account/src/main/resources/views/Invoice.xml
Warning hilite was always taking precedence over danger because of
overlapping conditions.
> invoice: fix hilighting for overdue bills

- axelor-base/src/main/resources/views/FiscalPosition.xml
- axelor-base/src/main/resources/views/TaxEquiv.xml
> Anomaly #11797 ACCOUNTING : Fiscal position interface rework

- CHANGELOG.md
- axelor-base/src/main/java/com/axelor/apps/base/web/UserController.java
- axelor-base/src/main/resources/views/User.xml
Reverts axelor/axelor-business-suite#1723, because changes are not included in rc2 release of adk.
> Revert "Anomaly #11834 Upgrade : save user-form and user-preference-form"

- axelor-account/src/main/resources/reports/Invoice.rptdesign
Enlarge BIC/IBAN/Bank address value fields and format IBAN according to
standard.
> Invoice: fix bank contact info formatting

- axelor-human-resource/src/main/resources/views/Product.xml
> Anomaly #11615 PRODUCT : activity

- CHANGELOG.md
> Anomaly #11229 PRODUCT: Change weight by mass

- axelor-account/src/main/resources/reports/Invoice.rptdesign
- axelor-account/src/main/resources/views/Invoice.xml
This is far more convenient and consistent. Moreover, it was impossible
to add new lines in existing version
> invoice: be consistent with order by allowing HTML in notes

- CHANGELOG.md
- axelor-purchase/src/main/java/com/axelor/apps/purchase/web/PurchaseOrderLineController.java
- axelor-purchase/src/main/resources/views/PurchaseOrderLine.xml
- axelor-supplier-management/src/main/java/com/axelor/apps/suppliermanagement/web/PurchaseOrderSupplierLineController.java
Filtered domains of both supplierPartner fields in purchase-order-line-form and purchase-order-supplier-line-form. Also modified generated supplier requests generation for coherence (no supplier request is generated for the company making the purchase order).
> Dev 10090 10090 : Added domain filters to supplierPartner fields + filter to generateSupplierRequests button

- axelor-account/src/main/java/com/axelor/apps/account/service/AccountingSituationServiceImpl.java
Fix NPE when client partner has no accounting situation when getting
company bank details from partner.
> RM12314: NPE in getCompanySalesBankDetails.

- CHANGELOG.md
- axelor-crm/src/main/resources/data-init/input-config.xml
- axelor-production/src/main/resources/data-init/input-config.xml
- axelor-purchase/src/main/resources/data-init/input-config.xml
- axelor-sale/src/main/resources/data-init/input-config.xml
- axelor-stock/src/main/resources/data-init/input-config.xml
> Restore missing app data init for CRM and Production.

- CHANGELOG.md
- axelor-crm/src/main/java/com/axelor/apps/crm/web/OpportunityController.java
Opportunity: fix error in grid view when clicking on "Assign to me"
button without having selected any lines.
> RM12629: fix NPE in grid view.

- axelor-account/src/main/resources/reports/Invoice.rptdesign
French law makes invoice reference mandatory on every pages, along with
the page number and the total number of pages, so put the reference
right below the page number.
> invoice report: add invoice reference in footer

- CHANGELOG.md
- axelor-admin/build.gradle
- axelor-admin/src/main/java/com/axelor/auth/service/PermissionAssistantService.java
- axelor-admin/src/main/resources/domains/PermissionAssistant.xml
- axelor-tool/src/main/java/com/axelor/apps/tool/StringTool.java
Permission assistant: use language configuration.
> Permission assistant: use language configuration.

- axelor-contract/src/main/resources/views/Contract.xml
when invoicing management is disabled on contract
> RM14109: Hide contractLineList

- CHANGELOG.md
- axelor-stock/src/main/resources/domains/FreightCarrierCustomerAccountNumber.xml
> Anomaly RM#13692 Stock - FreightCarrierCustomerAccountNumber : index length issue

- axelor-admin/src/main/java/com/axelor/apps/base/job/ThreadedJob.java
- axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/ebics/service/EbicsCertificateService.java
- axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/ebics/service/EbicsService.java
- axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/service/batch/BatchBankStatement.java
- axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/web/AccountingBatchController.java
Also clear persistence context after job completion.
> RM15100: trace bank statement batch errors

- CHANGELOG.md
- axelor-sale/src/main/resources/demo/en/base_appSale.csv
- axelor-sale/src/main/resources/demo/fr/base_appSale.csv
- axelor-sale/src/main/resources/views/AppSale.xml
Also fix demo data. If manageSaleOrderVersion is enabled, we should also
enable printingOnSOFinalization.
> RM12347: fix unresolved action error in App Config

- axelor-stock/src/main/resources/views/Menu.xml
- axelor-stock/src/main/resources/views/StockMove.xml
Using a dummy field to get the boolean configurations of StockMove
> RM15919: fix bug of process 'realize a stock move'

- axelor-studio/src/main/resources/views/Menu.xml
Error introduced in commit fa21211fb9ecfd45489a35421cd16827bddc4cf3.
> RM13423: Fix error overwriting new menus of studio.

- axelor-account/src/main/java/com/axelor/apps/account/service/ReconcileGroupServiceImpl.java
- axelor-account/src/main/resources/domains/ReconcileGroup.xml
- axelor-account/src/main/resources/i18n/messages.csv
- axelor-account/src/main/resources/i18n/messages_en.csv
- axelor-account/src/main/resources/i18n/messages_fr.csv
- axelor-account/src/main/resources/views/Selects.xml
- axelor-production/src/main/java/com/axelor/apps/production/db/repo/ProductProductionRepository.java
- Now, ReconcileGroup will not get removed from Reconcile
when Reconcile gets Unreconcile(dereconcile)
- ReconcileGroup status gets updated to 'Unlettered' when all Reconcile
status is cancelled.
> Feature RM#17415 - Add new status in ReconcileGroup

- CHANGELOG.md
- axelor-account/src/main/java/com/axelor/apps/account/db/repo/InvoiceManagementRepository.java
validatedByUser is set null already
> RM#18018 COPY OF INVOICE : empty fields

- CHANGELOG.md
- axelor-base/src/main/java/com/axelor/apps/base/service/advanced/imports/AdvancedImportServiceImpl.java
> Anomaly RM#19448 Advanced Data import : error indexOutOfBound

- CHANGELOG.md
- axelor-account/src/main/java/com/axelor/apps/account/service/payment/PayboxService.java
- axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/ebics/certificate/KeyStoreManager.java
- axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/ebics/service/EbicsCertificateService.java
> Fix ClassCastException when adding certificates

- axelor-account/src/main/java/com/axelor/apps/account/service/move/MoveLineService.java
- axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/ebics/script/EbicsUserImport.java
> Fix unreported CertificateException

- axelor-account/src/main/java/com/axelor/apps/account/service/TaxPaymentMoveLineService.java
- axelor-account/src/main/java/com/axelor/apps/account/service/TaxPaymentMoveLineServiceImpl.java
- axelor-account/src/main/java/com/axelor/apps/account/service/move/MoveServiceImpl.java
- axelor-account/src/main/java/com/axelor/apps/account/web/TaxPaymentMoveLineController.java
- axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/ebics/web/EbicsRequestLogController.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/web/expense/ExpenseController.java
- axelor-supplychain/src/main/java/com/axelor/csv/script/ImportSupplyChain.java
Fix typo in filter used in
ImportSupplyChain#generateManualTrackingNumber.
Addresses RM-18984
> Fix typo in filter

- CHANGELOG.md
- axelor-business-project/src/main/resources/reports/Project.rptdesign
> RM#21748 Business Project report : refund should be negative in the chart

- CHANGELOG.md
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/batch/BatchReminderTimesheet.java
- axelor-message/src/main/java/com/axelor/apps/message/service/MessageServiceImpl.java
> Wait for closed entity manager in parent thread

- CHANGELOG.md
- axelor-base/src/main/resources/domains/Product.xml
Reverts axelor/axelor-open-suite#4758
> Revert "Feature #24310 PRODUCT : default supplier"

- axelor-base/src/main/resources/views/BankDetails.xml
- Add balance button in bank details tree view
> [Feature #24971] COMPANY : bank details tree view

- CHANGELOG.md
- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/StockMoveInvoiceServiceImpl.java
> RM#25298 StockMove: Fix issue of generated invoice with empty invoiceLines

- CHANGELOG.md
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/batch/BatchTimesheetReminder.java
> Anomaly RM#25962: HR-Batch : Fix Timesheet Reminder send email

- CHANGELOG.md
- axelor-base/src/main/resources/domains/Canton.xml
- axelor-base/src/main/resources/domains/City.xml
- axelor-base/src/main/resources/domains/Country.xml
- axelor-base/src/main/resources/domains/Department.xml
- axelor-base/src/main/resources/domains/Region.xml
RM#13698 geographical entities are not cacheable anymore to improve peformance
> RM#13698 geographical entities are not cacheable anymore

- CHANGELOG.md
- axelor-supplychain/src/main/resources/views/Menu.xml
- axelor-supplychain/src/main/resources/views/Product.xml
RM#26145
In supplychain-stock-details-by-product-form, company now autofill with user's active company when this view entry is from menu
> RM#26145  supplychain-stock-details-by-product-form - Default company value

- axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/service/bankorder/BankOrderServiceImpl.java
- Update the condition to set validate status with its process
> [Feature #25847] Bank order workflow - update

- CHANGELOG.md
- axelor-admin/src/main/resources/views/GlobalTrackingConfigurationLine.xml
> RM #26848 : GlobalTrackingConf.Lines, display correctly boolean titles

- axelor-human-resource/src/main/java/com/axelor/apps/hr/mobile/HumanResourceMobileController.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/batch/BatchSeniorityLeaveManagement.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/leave/LeaveServiceImpl.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/web/leave/LeaveController.java
- axelor-human-resource/src/main/resources/data-init/input/hr_leaveReason.csv
- axelor-human-resource/src/main/resources/demo/en/base_leaveTemplate.csv
- axelor-human-resource/src/main/resources/demo/en/hr_leaveLine.csv
- axelor-human-resource/src/main/resources/demo/en/hr_leaveReason.csv
- axelor-human-resource/src/main/resources/demo/fr/base_leaveTemplate.csv
- axelor-human-resource/src/main/resources/demo/fr/hr_leaveLine.csv
- axelor-human-resource/src/main/resources/demo/fr/hr_leaveReason.csv
- axelor-human-resource/src/main/resources/domains/LeaveReason.xml
- axelor-human-resource/src/main/resources/views/LeaveLine.xml
- axelor-human-resource/src/main/resources/views/LeaveReason.xml
- changelogs/unreleased/RenameLeaveReasonNameField.yml
And consequent changes in java & xml
RM #26192
> RM #26192 : LeaveReason: Reaname 'leaveReason' fieldinto 'name'

- axelor-account/src/main/java/com/axelor/apps/account/service/AccountingSituationServiceImpl.java
- Code cleaner than before
RM #24606 (cherry pick from 5.2)
> RM #24606 : AccountingSituationService, create constructor for account

- axelor-account/src/main/java/com/axelor/apps/account/service/AccountingSituationServiceImpl.java
- Code cleaner than before
RM #24606
> RM #24606 : AccountingSituationService : create constructor for account

- axelor-account/src/main/resources/data-init/app/en/base_sequence.csv
> RM #21914 : ReconcileGroup data init fix (en) version

- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/workflow/WorkflowVentilationServiceSupplychainImpl.java
- building bugfix after cherry-pick from 5.3 -> the code did call a method missing from 5.2
- injection move outside the for-loop
RM #27754 (correction)
> RM #27754 (2) : Invoice, ventilation process unit check code correction

- axelor-business-project/src/main/java/com/axelor/apps/businessproject/service/WorkflowVentilationProjectServiceImpl.java
- subclass changed to make extension right after 1st correction
RM #27754 (second code correction)
> Invoice, ventilation process unit check code second correction

- axelor-business-project/src/main/java/com/axelor/apps/businessproject/service/WorkflowVentilationProjectServiceImpl.java
- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/workflow/WorkflowVentilationServiceSupplychainImpl.java
- injections moved on the constuctor to improve performances on mass ventilation
RM #27754 (correction)
> Invoice, ventilation process unit check code correction

- CHANGELOG.md
- axelor-bank-payment/src/main/resources/demo/bank-payment-config.xml
- axelor-bank-payment/src/main/resources/domains/BankOrderEconomicReason.xml
- demo data field 'name' is not filled on loading for this Model
RM #27485
> BankOrderEconomicReason change config for demo data

- CHANGELOG.md
- axelor-bank-payment/src/main/resources/views/BankStatement.xml
- axelor-bank-payment/src/main/resources/views/BankStatementLine.xml
Add ID to BankStaement grid view
Add Bank Statement reference field in BankStatementLines view which are outside BankStatement form view
RM #24418
> RM #24418 : BankStatement[Line] view changes

- CHANGELOG.md
- axelor-account/src/main/resources/views/AccountingBatch.xml
- Add required on year field to avoid NPE on 'close annual accounts ...' option
- Change requiredIf condition to fix issue which blocked the saving and so the run of a batch.
RM #20529
> RM #20529 : AccountingBatch fix required fields

- CHANGELOG.md
- axelor-base/src/main/java/com/axelor/apps/base/service/message/MessageServiceBaseImpl.java
- axelor-crm/src/main/java/com/axelor/apps/crm/message/MessageServiceCrmImpl.java
- axelor-message/src/main/java/com/axelor/apps/message/module/MessageModule.java
- axelor-message/src/main/java/com/axelor/apps/message/service/MessageServiceImpl.java
- axelor-message/src/main/java/com/axelor/apps/message/service/SendMailQueueService.java
Fix an issue where too many calls to mailBuilder.send were made, causing
an exception caused by the smtp server.
Fixes RM28522
> Send mail message: fix mails not sent

- axelor-account/src/main/resources/views/MoveLine.xml
- axelor-bank-payment/src/main/resources/views/BankStatement.xml
- changelogs/unreleased/add-2-dashlets.yml
In move-line-form add a dashlet to display associated bank reconciliation lines
In bank-statement-form add a dashlet to display associated move lines
RM #22940
> RM #22940 : MoveLine & BankSatement, add 2 new dashlet in form views

- CHANGELOG.md
- axelor-account/src/main/resources/views/Account.xml
- axelor-account/src/main/resources/views/MoveLine.xml
> RM28239 : Fix wrong move line grid view in account (#5457)

- axelor-base/src/test/java/com/axelor/apps/base/test/UserServiceTest.java
Fix UserServiceTest.java by installing AppModule in configure method
> Fix UserServiceTest

- axelor-account/src/main/resources/i18n/messages_fr.csv
- axelor-account/src/main/resources/views/DebtRecovery.xml
- axelor-account/src/main/resources/views/Invoice.xml
identation has also been fixed
> [dev-27896] added 'blocked invoices' tab in DebtRecovery

- CHANGELOG.md
- axelor-base/src/main/java/com/axelor/apps/base/ical/ICalendarService.java
- axelor-crm/src/main/java/com/axelor/apps/crm/service/CalendarService.java
ICalendar : Fix IndexOutOfBound Exception & Manage synchronization select.
> Anomaly RM#30251 ICalendar : Synchronisation issues

- axelor-base/src/main/java/com/axelor/apps/base/db/repo/UserBaseRepository.java
Default language is based on application.ppties even if the user created automatically from java process
> RM20115 default language is based on application.ppties for users created automatically

- CHANGELOG.md
- axelor-studio/src/main/resources/data-export/export-bpm.tmpl
- axelor-studio/src/main/resources/data-import/import-bpm.xml
> Anomaly RM#30203 Studio: Menubuilder export and import is not working properly

- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/StockMoveLineServiceSupplychainImpl.java
- changelogs/unreleased/move_stock_line_fixed_conversion_issue_when_changing_values.yml
> Anomaly #32188 Fixed conversion issue when computing StockMoveLines

- axelor-account/src/main/java/com/axelor/apps/account/web/FixedAssetController.java
- changelogs/unreleased/fixed-asset-validate.yml
> Anomaly #31702 Fixed issue when validating a Fixed Asset

- axelor-bank-payment/src/main/resources/views/BankStatementLineAFB120.xml
- changelogs/unreleased/bad_hilite_in_bank_statement_line_grid.yml
> Anomaly #31142 BankStatementLine : hilite is now correct in bank-statement-line-grid

- axelor-stock/src/main/resources/demo/en/stock_inventory.csv
- axelor-stock/src/main/resources/demo/fr/stock_inventory.csv
- axelor-stock/src/main/resources/demo/stock-config.xml
- changelogs/unreleased/inventory_add_missing_field_in_demo_data.yml
> Anomaly #31585 Added missing fields in Inventory demo import

- axelor-base/src/main/java/com/axelor/apps/base/service/administration/SequenceService.java
- axelor-message/src/main/java/com/axelor/apps/message/service/SendMailQueueService.java
- changelogs/unreleased/sequence-avoid-concurrent-exception.yml
> Manage concurrent next number call for sequence

- axelor-project/src/main/resources/views/Project.xml
- changelogs/unreleased/fix-project-grid-view.yml
> Anomaly #32587 : PROJECT : grid view

- axelor-project/src/main/resources/views/TeamTask.xml
- changelogs/unreleased/team-task-project-field.yml
-User cannot choose a closed or cancelled project anymore
Anomaly #30995
> Anomaly #30995 Added domain on project field in TeamTask form view

- axelor-supplychain/src/main/resources/views/PartnerSupplychainLink.xml
- changelogs/unreleased/partner-supplychain-link-merge-fields-and-viewers.yml
Modify PartnerSupplychainLink grid views to merge partnerSupplychainLinkType fields and viewers into one target-name field
> Modify PartnerSupplychainLink grid views

- axelor-cash-management/src/main/java/com/axelor/apps/cash/management/service/ForecastService.java
- changelogs/unreleased/fix-bad-forecast-type.yml
… now (a posiive value for a forecast amount represents an ingoing transaction and a negative value represents an outgoing transaction)
> Anomaly #31588 : FORECAST RECAP : manual forecast

- axelor-account/src/main/java/com/axelor/apps/account/service/AccountingReportServiceImpl.java
- axelor-account/src/main/java/com/axelor/apps/account/service/MoveLineExportServiceImpl.java
- axelor-account/src/main/java/com/axelor/apps/account/service/ReconcileServiceImpl.java
- axelor-account/src/main/java/com/axelor/apps/account/service/move/MoveTemplateService.java
- axelor-admin/src/main/java/com/axelor/apps/base/service/app/AppServiceImpl.java
- axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/ebics/service/EbicsPartnerServiceImpl.java
- axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/ebics/service/EbicsService.java
- axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/ebics/xml/UserSignatureVerify.java
- axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/service/bankorder/BankOrderServiceImpl.java
- axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/service/bankorder/file/transfer/BankOrderFileAFB160Service.java
- axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/service/bankorder/file/transfer/BankOrderFileAFB320XCTService.java
- axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/service/bankstatement/BankStatementService.java
- axelor-base/src/main/java/com/axelor/apps/base/service/DuplicateObjectsService.java
- axelor-base/src/main/java/com/axelor/apps/base/web/DuplicateObjectsController.java
- axelor-contract/src/main/java/com/axelor/apps/contract/db/repo/ContractRepository.java
- axelor-crm/src/main/java/com/axelor/apps/crm/web/OpportunityController.java
- axelor-docusign/src/main/java/com/axelor/apps/docusign/web/DocuSignEnvelopeSettingController.java
- axelor-production/src/main/java/com/axelor/apps/production/service/PurchaseOrderServiceProductionImpl.java
@ale-axelor Could you review and accept this PR please? There are no functional changes but only technical improvements in order to remove some warnings and apply some sonarlint recommendations.
> Fix java warnings and sonar infos

- axelor-production/src/main/java/com/axelor/apps/production/service/costsheet/CostSheetServiceImpl.java
- changelogs/unreleased/cost-sheet-computation-fix-rounding.yml
> Cost Sheet Line: Fix rounding issue

- axelor-stock/src/main/resources/views/StockConfig.xml
- axelor-supplychain/src/main/resources/views/StockConfig.xml
- changelogs/unreleased/filter-all-stock-locations-of-stockConfig-per-company.yml
> all stock locations filtered per company

- axelor-account/src/main/resources/reports/AccountingReportType1.rptdesign
- axelor-account/src/main/resources/reports/AccountingReportType7.rptdesign
- changelogs/unreleased/fix-accouting-report-type-select.yml
ERROR: column accountingreport.type_select does not exist
> Anomaly RM#35208 ACCOUNTING REPORT : General ledger

- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/SaleOrderServiceSupplychainImpl.java
> Feature #33031 Fix issue with multiple injection of the same repository in SaleOrdServiceSupplychainImpl class

- axelor-account/src/main/resources/views/InvoicePayment.xml
- Moved typeSelect field to the top of the form view
> [Anomaly #36270] INVOICE PAYMENT : type

- axelor-purchase/src/main/resources/reports/PurchaseOrder.rptdesign
- axelor-sale/src/main/resources/reports/SaleOrder.rptdesign
> Anomaly RM#36923 Sale order and purchase order report: translatable unit field not working

- axelor-base/src/main/java/com/axelor/apps/base/service/MailServiceBaseImpl.java
-for field to/cc/bcc recipients and subject on sending email
> RM#25608 MAIL MESSAGE : Used template's context to evaluate expression

- axelor-production/src/main/resources/views/CostSheetLine.xml
- changelogs/unreleased/fix-cost-sheet-line-icons.yml
replace typeSelect by typeSelectIcon
> #37781 COSTSHEET : type is not displaying the correct icon

- axelor-production/src/main/java/com/axelor/apps/production/service/configurator/ConfiguratorBomServiceImpl.java
- axelor-production/src/main/resources/data-export/export-production-configurator-creator.tmpl
- axelor-production/src/main/resources/demo/en/production_configuratorCreator.xml
- axelor-production/src/main/resources/demo/fr/production_configuratorCreator.xml
- axelor-production/src/main/resources/domains/ConfiguratorBOM.xml
- axelor-production/src/main/resources/views/ConfiguratorBOM.xml
- axelor-sale/src/main/resources/data-import/import-configurator-creator-config.xml
- axelor-sale/src/main/resources/views/ConfiguratorCreator.xml
- changelogs/unreleased/configurator-bom-workshop.yml
…llow define by script + update configurator export/import/demo data + fix on def work center as formula on configurator import
> Feature #39302 Configurator bom workshop stock location

- axelor-production/src/main/resources/views/OperationOrder.xml
- changelogs/unreleased/fix-operation-order-stock-move-consumed-product-panels-display.yml
> Anomaly #39578 operation order fix panels display

- axelor-sale/src/main/java/com/axelor/apps/sale/service/configurator/ConfiguratorServiceImpl.java
- changelogs/unreleased/configurator-fill-many-to-many-fields.yml
Allow to fill a many-to-many field from a formula.
RM39729
> Configurator: allow to fill a many-to-many field

- axelor-base/src/main/java/com/axelor/apps/base/service/PriceListService.java
- axelor-base/src/main/resources/i18n/messages_fr.csv
- axelor-base/src/main/resources/views/UnitConversion.xml
- changelogs/unreleased/37322.yml
groovy field already done 
added help section in panel
> 37322 UNIT CONVERSION : formula

- axelor-account/src/main/java/com/axelor/apps/account/service/move/MoveCreateService.java
- axelor-account/src/main/java/com/axelor/apps/account/service/move/MoveCreateServiceImpl.java
- axelor-account/src/main/java/com/axelor/apps/account/service/move/MoveLineServiceImpl.java
- axelor-account/src/main/java/com/axelor/apps/account/service/move/MoveServiceImpl.java
- axelor-account/src/main/java/com/axelor/apps/account/service/move/MoveValidateService.java
- axelor-account/src/main/java/com/axelor/apps/account/web/MoveController.java
- axelor-account/src/main/java/com/axelor/apps/account/web/MoveLineController.java
- axelor-account/src/main/java/com/axelor/apps/account/web/PaymentMoveLineDistributionController.java
- axelor-account/src/main/resources/views/Move.xml
- axelor-bank-payment/src/main/java/com/axelor/apps/bankpayment/service/move/MoveServiceBankPaymentImpl.java
Reverts axelor/axelor-open-suite#6823
> Revert "Anomaly #41246 : Refactor to comply code convention on wip-6.2-accounting"

- axelor-cash-management/src/main/resources/views/Charts.xml
- axelor-cash-management/src/main/resources/views/ForecastRecap.xml
> Forecast recap: fix on forecast report display

- axelor-account/src/main/java/com/axelor/apps/account/service/moveline/MoveLineCreateServiceImpl.java
- axelor-account/src/main/resources/views/MoveLine.xml
Also fixed onChange on debit and credit for moveLine
> 42532 set tax line when auto generate moveLine tax line

- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/leave/LeaveService.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/leave/LeaveServiceImpl.java
- axelor-human-resource/src/main/resources/demo/en/hr_leaveLine.csv
- axelor-human-resource/src/main/resources/demo/fr/hr_leaveLine.csv
- axelor-human-resource/src/main/resources/demo/leave-config.xml
- changelogs/unreleased/43178-fixed-demo-data-of-leave-lines-not-having-a-name.yml
Add missing override, rewrite leave line creation methods. This should
not induce any behavior change.
RM43178
> HR Leave: refactor code

- axelor-account/src/main/java/com/axelor/apps/account/service/moveline/MoveLineComputeAnalyticServiceImpl.java
- axelor-account/src/main/java/com/axelor/apps/account/service/moveline/MoveLineService.java
- axelor-account/src/main/java/com/axelor/apps/account/service/moveline/MoveLineServiceImpl.java
- axelor-account/src/main/java/com/axelor/apps/account/web/AccountController.java
- axelor-account/src/main/java/com/axelor/apps/account/web/MoveController.java
- axelor-account/src/main/java/com/axelor/apps/account/web/MoveLineController.java
- axelor-account/src/main/resources/i18n/messages_fr.csv
- axelor-account/src/main/resources/views/Account.xml
- axelor-account/src/main/resources/views/MoveLine.xml
Reverts axelor/axelor-open-suite#6916
> Revert "42059 config analytic"

- axelor-account/src/main/java/com/axelor/apps/account/service/fixedasset/AbstractFixedAssetLineComputationServiceImpl.java
- axelor-account/src/main/java/com/axelor/apps/account/service/fixedasset/FixedAssetGenerationServiceImpl.java
- axelor-account/src/main/java/com/axelor/apps/account/service/fixedasset/FixedAssetLineComputationService.java
- axelor-account/src/main/java/com/axelor/apps/account/service/fixedasset/FixedAssetLineEconomicUpdateComputationServiceImpl.java
- axelor-account/src/main/java/com/axelor/apps/account/service/fixedasset/FixedAssetLineServiceImpl.java
- axelor-account/src/main/resources/views/AnalyticDistributionTemplate.xml
- axelor-account/src/main/resources/views/FixedAsset.xml
- axelor-account/src/test/java/com/axelor/apps/account/service/fixedasset/TestFixedAssetLineComputationService.java
Fix for wip-6.2-feature-fixed-assets
> Anomaly #43719:  fixed ArithmeticException on imported fixedAsset

- axelor-account/src/main/java/com/axelor/apps/account/service/invoice/InvoiceTermServiceImpl.java
- axelor-account/src/main/resources/views/AccountConfig.xml
- axelor-account/src/main/resources/views/Invoice.xml
- axelor-account/src/main/resources/views/InvoiceTerm.xml
- axelor-account/src/main/resources/views/InvoiceTermPayment.xml
- axelor-account/src/main/resources/views/Menu.xml
- axelor-account/src/main/resources/views/Partner.xml
- changelogs/unreleased/fix-financial-discount-display-and-management-on-invoice-term.yml
when disabled in account config
> RM43779 - do not display and manage financial discount on invoiceTerms ..

- axelor-account/src/main/resources/views/AccountConfig.xml
- axelor-account/src/main/resources/views/AccountingSituation.xml
> RM43907 - account status - add domain on fields related to invoice term process

- axelor-sale/src/main/java/com/axelor/apps/sale/service/saleorder/SaleOrderLineServiceImpl.java
- changelogs/unreleased/fix-issue-on-pricing-logs.yml
> RM#44314 Fix issue on pricing logs

- axelor-base/src/main/java/com/axelor/apps/base/service/ProductCategoryService.java
- axelor-base/src/main/java/com/axelor/apps/base/service/ProductCategoryServiceImpl.java
- axelor-production/src/main/java/com/axelor/apps/production/service/MrpServiceProductionImpl.java
- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/MrpServiceImpl.java
> MRP: Refactor product category call in MRP service

- axelor-stock/src/main/java/com/axelor/apps/stock/exception/IExceptionMessage.java
- axelor-stock/src/main/java/com/axelor/apps/stock/web/StockMoveController.java
- axelor-stock/src/main/resources/i18n/messages.csv
- axelor-stock/src/main/resources/i18n/messages_en.csv
- axelor-stock/src/main/resources/i18n/messages_fr.csv
- changelogs/unreleased/stock-move-add-server-side-check.yml
> Stock move realization: add server side check.

- axelor-production/src/main/java/com/axelor/apps/production/web/ManufOrderController.java
- changelogs/unreleased/fix-regression-on-out-sourcing-purchase-order-generation-on-manuf-orders.yml
> Anomaly #46094 Fix regression on ticket #25001

- axelor-project/src/main/java/com/axelor/apps/project/service/ProjectMenuServiceImpl.java
> Feature #45950: Menu for all tasks

- axelor-account/src/main/java/com/axelor/apps/account/web/AccountingReportController.java
- axelor-account/src/main/resources/domains/AccountingReportType.xml
- axelor-account/src/main/resources/i18n/messages_en.csv
- axelor-account/src/main/resources/i18n/messages_fr.csv
- axelor-account/src/main/resources/views/AccountingReport.xml
- axelor-account/src/main/resources/views/AccountingReportType.xml
- changelogs/unreleased/46411.yml
Allow accounting users to use predefined accounting report templates
> feature:: #46411

- axelor-production/src/main/java/com/axelor/apps/production/service/productionorder/ProductionOrderService.java
Signed-off-by: David Trochel <d.trochel@axelor.com>
> Fix Javadoc in ProductionOrderService

- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/timesheet/TimesheetLineServiceImpl.java
Anomaly #47861: Timesheet : npe if no user selected
> Anomaly #47861:Check user is not null in timesheet

- axelor-sale/src/main/resources/domains/AdvancePayment.xml
Remove tracking of a field that does not exist in the model.
RM48710
> Advance Payment: remove purchase order field tracking

- axelor-talent/src/main/resources/views/Charts.xml
To prepare a future AOP update, need to change this query.
In AOP 5.4.10, this change will not affect the behavior of the
application.
RM48829
> Employee: Fix query in training chart

- axelor-human-resource/src/main/java/com/axelor/apps/hr/db/repo/EmployeeHRRepository.java
- changelogs/unreleased/44090-fix-partner-on-employee-creation
Reverts axelor/axelor-open-suite#8033
> #44090: Fix employee creation: update companySet and isEmployee field

- axelor-supplychain/src/main/java/com/axelor/csv/script/ImportSupplyChain.java
Improve demo data result by correctly make a rollback in case there is an issue in process/data.
RM49799
> Improve exception management on demo data import

- axelor-base/src/main/resources/views/BankDetails.xml
- changelogs/unreleased/fix-missing-fields-bank-details-view.yml
Reverts axelor/axelor-open-suite#8252
> Revert "RM#50121 : Fix missing fields when creating bank detials from comapny"

- axelor-base/src/main/resources/views/BankDetails.xml
- changelogs/unreleased/fix-missing-fields-bank-details-view.yml
Reverts axelor/axelor-open-suite#8260
> RM#50121 : Fix missing fields when creating bank detials from comapny

- axelor-account/src/main/resources/views/Reimbursement.xml
- changelogs/unreleased/50227-fix-bank-details-and-move-line-filter-by-filtering-by-partner.yml
Reverts axelor/axelor-open-suite#8335
> Revert "RM#50227: REIMBURSEMENT: corrected bank details and move line filter …"

- axelor-account/src/main/resources/views/Reimbursement.xml
- changelogs/unreleased/50227-fix-bank-details-and-move-line-filter-by-filtering-by-partner.yml
Reverts axelor/axelor-open-suite#8336
> RM#50227: REIMBURSEMENT: corrected bank details and move line filter

- axelor-account/src/main/resources/views/Invoice.xml
Reverts axelor/axelor-open-suite#8442
> Revert "RM#51470 : Open invoice term in another tab from invoice"

- axelor-base/src/main/resources/domains/City.xml
- changelogs/unreleased/50721.yml
Updating script has been made in:
https://git.axelor.com/abs/abs-scripts/-/commit/6e3827df934062d3482c20b7bf87c8742b63f259
> RM#50721:  custom field for cities to see both city name and postal code

- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/PurchaseOrderServiceSupplychainImpl.java
- changelogs/unreleased/47168-fix-JNPE-on-PO-generation.yml
> Remove NPE on generating PO with shipment mode

- axelor-account/src/main/java/com/axelor/apps/account/module/AccountModule.java
- axelor-account/src/main/java/com/axelor/apps/account/service/analytic/AnalyticMoveLineGenerateRealService.java
- axelor-account/src/main/java/com/axelor/apps/account/service/analytic/AnalyticMoveLineGenerateRealServiceImpl.java
- axelor-account/src/main/java/com/axelor/apps/account/service/moveline/MoveLineCreateServiceImpl.java
- axelor-business-project/src/main/java/com/axelor/apps/businessproject/service/ExpenseServiceProjectImpl.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/module/HumanResourceModule.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/analytic/AnalyticMoveLineGenerateRealServiceHrImpl.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/expense/ExpenseServiceImpl.java
- changelogs/unreleased/52645-fix-JNPE-on-expense-ventilation.yml
Error happened because analytic move line was not correctly generated
from expense line.
RM52645
> Expense: fix JNPE on ventilation

- axelor-sale/src/main/java/com/axelor/apps/sale/service/saleorder/SaleOrderLineServiceImpl.java
- changelogs/unreleased/fix-sale-order-complementary-product-generation.yml
> Sale order: fix generating lines from partner complementary products

- axelor-account/src/main/java/com/axelor/apps/account/service/ReconcileServiceImpl.java
Signed-off-by: David Trochel <d.trochel@axelor.com>
> RM#47840 Rename udpatePaymentTax into updatePaymentTax

- axelor-bank-payment/src/main/resources/views/PaymentSession.xml
> Remove duplicated payment session grid view

- axelor-account/src/main/resources/views/InvoiceLine.xml
- changelogs/unreleased/54615.yml
Reverts axelor/axelor-open-suite#8986
> Revert "54615 - INVOICELINE : Cannot invoke method toUpperCase() on null object"

- axelor-account/src/main/resources/views/InvoiceLine.xml
- changelogs/unreleased/54615.yml
Reverts axelor/axelor-open-suite#8992
> 54615 - INVOICELINE : Cannot invoke method toUpperCase() on null object

- axelor-account/src/main/java/com/axelor/apps/account/module/AccountModule.java
- axelor-account/src/main/java/com/axelor/apps/account/service/fixedasset/FixedAssetDerogatoryLineServiceImpl.java
- axelor-account/src/main/java/com/axelor/apps/account/service/fixedasset/FixedAssetLineService.java
- axelor-account/src/main/java/com/axelor/apps/account/service/fixedasset/FixedAssetLineServiceImpl.java
- axelor-account/src/main/java/com/axelor/apps/account/service/fixedasset/FixedAssetLineToolService.java
- axelor-account/src/main/java/com/axelor/apps/account/service/fixedasset/FixedAssetLineToolServiceImpl.java
- axelor-account/src/test/java/com/axelor/apps/account/service/fixedasset/TestFixedAssetLineToolService.java
- changelogs/unreleased/fixed-asset-derogatory-prorata-54814.yml
Some dates were not grouped correctly during the computation.
RM54814
> Fixed asset: fix computation for derogatory lines

- axelor-base/src/main/java/com/axelor/apps/base/module/BaseModule.java
- axelor-base/src/main/java/com/axelor/apps/base/service/administration/SequenceVersionGeneratorQueryService.java
- axelor-base/src/main/java/com/axelor/apps/base/service/administration/SequenceVersionGeneratorQueryServiceImpl.java
- axelor-base/src/main/java/com/axelor/apps/base/service/administration/SequenceVersionGeneratorServiceImpl.java
- axelor-base/src/test/java/com/axelor/apps/base/service/administration/TestSequenceVersionGeneratorService.java
- axelor-tool/src/main/java/com/axelor/apps/tool/date/DateTool.java
- axelor-tool/src/test/java/com/axelor/apps/tool/TestDateTool.java
- changelogs/unreleased/fix-sequence-version-generation-gap.yml
Add unit test and fix an issue if there is a gap in version RM55300
> Sequence version refactor and fix

- axelor-account/src/main/java/com/axelor/apps/account/db/repo/MoveManagementRepository.java
Reverts axelor/axelor-open-suite#9270
> Revert "56962 - MOVE / MOVE LINE / INVOICETERM LIST _ ApplyFinancialDiscount …"

- axelor-stock/src/main/java/com/axelor/apps/stock/service/StockMoveToolServiceImpl.java
- changelogs/unreleased/59675.yml
Stock Move -> exTaxTotal rounding is now realized on stock move lines and not on stock move anymore
> 59675  : Stock Move -> exTaxTotal rounding

- axelor-gdpr/src/main/resources/i18n/messages_fr.csv
> Fix typo in fr translation

- libs.gradle
> Downgrade XMLbeans dependency to match AOP version

- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/StockMoveServiceSupplychainImpl.java
- changelogs/unreleased/stock-move-error-without-supplychain.yml
> Stock move: fixed check on AppSupplychain

- axelor-business-production/src/main/java/com/axelor/apps/businessproduction/service/SaleOrderWorkflowServiceBusinessProductionImpl.java
- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/SaleOrderWorkflowServiceSupplychainImpl.java
Signed-off-by: David Trochel <d.trochel@axelor.com>
> RM#53996 Don't inject AppSupplychain and fix service visiblity

- axelor-bpm/build.gradle
- axelor-bpm/src/main/webapp/wkf-editor/token-assets/font-awesome/css/font-awesome.min.css
> BPM: exclude folder from licenseFormat

- axelor-mobile-settings/src/main/resources/apps/init-data/en/mobilesettings_mobileMenu.csv
- axelor-mobile-settings/src/main/resources/apps/init-data/fr/mobilesettings_mobileMenu.csv
> Fix mobile menu import data init

- axelor-base/src/main/resources/views/Selects.xml
Some select were defined twice because of exception and admin merge into base.
RM61301
> Remove duplicated selects

- axelor-base/src/main/java/com/axelor/apps/base/service/advancedExport/CsvExportGenerator.java
- axelor-base/src/main/java/com/axelor/auth/service/PermissionAssistantService.java
> Fix compilation warnings in csv services

- axelor-account/src/main/resources/FEC-config/import-FEC-config.xml
- changelogs/unreleased/63158-fec-import.yml
> Fixed issue when importing FEC

- axelor-account/src/main/resources/domains/MoveTemplate.xml
> Remove weird required expression in domain

- axelor-account/src/main/resources/views/MoveLine.xml
> Remove duplicated action-views

- axelor-account/src/main/resources/i18n/messages_fr.csv
- changelogs/unreleased/63884.yaml
> RM#63884 Added missing translation

- axelor-account/src/main/resources/views/MoveLine.xml
- changelogs/unreleased/63888.yml
Delete action 'action-record-analytic-distribution-type-select' since its not used anymore.
> RM#63888 Deleted non used action

- changelogs/unreleased/update-axelor-studio-to-1.0.1.yml
- libs.gradle
> Update axelor-studio to 6.0.1

- axelor-sale/src/main/java/com/axelor/apps/sale/service/configurator/ConfiguratorCreatorServiceImpl.java
- axelor-sale/src/main/resources/domains/ConfiguratorCreator.xml
- changelogs/unreleased/fix-configurator-deletion-of-attributes-not-taken-into-account.yml
> Anomaly RM#63800: Configurator - Removal of attributes and Indicators upon delete

- axelor-account/src/main/java/com/axelor/apps/account/service/move/record/MoveDefaultService.java
- axelor-account/src/main/java/com/axelor/apps/account/service/move/record/MoveDefaultServiceImpl.java
- axelor-account/src/main/java/com/axelor/apps/account/service/move/record/MoveGroupServiceImpl.java
- changelogs/unreleased/64600.yaml
Replace method called in onChange on field currency
> RM#64600 Move : can now change currency

- axelor-account/src/main/java/com/axelor/apps/account/service/move/record/MoveGroupServiceImpl.java
- axelor-account/src/main/java/com/axelor/apps/account/service/moveline/massentry/MoveLineMassEntryAttrsService.java
- axelor-account/src/main/java/com/axelor/apps/account/service/moveline/massentry/MoveLineMassEntryAttrsServiceImpl.java
- axelor-account/src/main/java/com/axelor/apps/account/service/moveline/massentry/MoveLineMassEntryGroupServiceImpl.java
> 64697 - Fix counterpart generation

- axelor-base/src/main/resources/i18n/messages_fr.csv
- changelogs/unreleased/birt-template-parameter-fix-translation-technical-term.yml
> Birt template parameter: fixed translation issue

- axelor-account/src/main/java/com/axelor/apps/account/web/MoveLineController.java
fix a previous regression causing an error on account change when cutoff dates were empty.
RM65353
> Move: fix a regression on account change

- axelor-business-project/src/main/java/com/axelor/apps/businessproject/service/ProjectBusinessServiceImpl.java
- axelor-business-project/src/main/resources/i18n/messages.csv
- axelor-business-project/src/main/resources/i18n/messages_en.csv
- axelor-business-project/src/main/resources/i18n/messages_fr.csv
- axelor-business-project/src/main/resources/views/ProjectTask.xml
- changelogs/unreleased/65128.yml
Fix issue with the 3 dashlets not working on the reporting panel of a task.
> RM#65128 ProjectTask : reportingPanel not working

- axelor-account/src/main/resources/reports/Invoice.rptdesign
- changelogs/unreleased/65766.yml
…nformation on Invoice Term are displayed on invoice BIRT
> Anomaly #65766: [Invoice BIRT] - If allowMultiInvoiceTerms is null, information on Invoice Term are displayed on invoice BIRT

- axelor-supplychain/src/main/java/com/axelor/csv/script/ImportSupplyChain.java
> RM#65953 Account : NPE when importing demo data

- axelor-crm/src/main/resources/views/Lead.xml
- changelogs/unreleased/66182.yml
Add a canNew on industrySector
Inverse primaryPostalCode and primaryCity
Hide lastEventDateT and nextScheduledEventDateT if empty
ActionsPanel hide it if grabLeadBtn, convertBtn, showPartnerBtn are hidden
> RM#66182 [Lead] lead-form: improvement

- axelor-base/src/main/resources/views/Menu.xml
- axelor-base/src/main/resources/views/Partner.xml
- changelogs/unreleased/66168.yml
Totally remove isEmployee from 'partner-form' and children.
> RM#66168 [CRM - Partner/Prospect] Fix for partner-customer-form with Partner isProspect

- axelor-sale/src/main/resources/views/SaleOrder.xml
- changelogs/unreleased/65735.yml
> RM#65735 SaleOrder template : Error on selecting a project

- axelor-crm/src/main/resources/views/ConvertLeadWizard.xml
"action-convert-lead-attrs-lead-to-contact-select-reset" on $leadToPartnerSelect
> RM#66358 CRM: Remove inexistent action call

- libs.gradle
> Upgrade axelor-studio version to 1.2.0

- axelor-account/src/main/java/com/axelor/apps/account/service/moveline/MoveLineConsolidateServiceImpl.java
- changelogs/unreleased/66684.yaml
Added missing service in constructor in 'MoveLineConsolidateServiceImpl'
> RM#66684 [Expense] NPE when ventilating an expense

- changelogs/unreleased/67109-bump-studio-version.yml
- libs.gradle
> Update axelor-studio from 1.2.0 to 1.2.1

- axelor-account/src/main/java/com/axelor/apps/account/service/AccountingReportServiceImpl.java
- changelogs/unreleased/65617.yml
AccountingReportService accountConfigService is already declared
> Anomaly #65613: [Sonar] Analysis 7.1.0

- axelor-account/src/main/resources/domains/AppInvoice.xml
> Remove "isInvoiceMoveConsolidated" from App Invoice tracking

- axelor-account/src/main/resources/domains/MoveLineMassEntry.xml
- axelor-base/src/main/resources/domains/ResearchParameter.xml
- axelor-base/src/main/resources/domains/ResearchParameterConfig.xml
- axelor-base/src/main/resources/domains/ResearchPrimaryKey.xml
- axelor-base/src/main/resources/domains/ResearchRequest.xml
- axelor-base/src/main/resources/domains/ResearchResultLine.xml
- axelor-budget/src/main/resources/domains/AccountConfig.xml
- axelor-budget/src/main/resources/domains/AnalyticAxisByCompany.xml
- axelor-budget/src/main/resources/domains/BudgetDistribution.xml
- axelor-budget/src/main/resources/domains/Move.xml
- axelor-budget/src/main/resources/domains/MoveLine.xml
- axelor-budget/src/main/resources/domains/PurchaseOrder.xml
- axelor-budget/src/main/resources/domains/PurchaseOrderLine.xml
- axelor-budget/src/main/resources/domains/SaleOrderLine.xml
- axelor-budget/src/main/resources/domains/User.xml
- axelor-crm/src/main/resources/domains/PartnerStatus.xml
> Update domain to remove outdated 'lang' attribute

- axelor-base/src/main/resources/views/AppBase.xml
> App Base: improve UI in config form view

- changelogs/unreleased/70013-update-studio.yml
- libs.gradle
> Update axelor-studio dependency to 1.2.4

- CONTRIBUTING.md
- SECURITY.md
> Add SECURITY.md

- axelor-supplychain/src/main/resources/views/SaleOrderLine.xml
> Remove duplicated action-record-sale-order-line-future-qty

- axelor-bank-payment/build.gradle
- changelogs/unreleased/70954-xml-dependency-issue.yml
> Update ebics-lib dependency to exclude xml-apis dependency

- changelogs/unreleased/70988-update-studio.yml
- libs.gradle
> Update axelor-studio to 1.3.3

- changelogs/unreleased/71451-update-studio.yml
- libs.gradle
> Update axelor-studio to 1.3.4

- axelor-production/src/main/java/com/axelor/apps/production/service/costsheet/UnitCostCalculationServiceImpl.java
- changelogs/unreleased/71286-fix-npe-on-selecting-product-in-unit-cost-calculation.yml
> Unit cost calculation: fixed product domain

- axelor-base/build.gradle
- axelor-base/src/main/java/com/axelor/apps/base/service/research/ResearchRequestServiceImpl.java
- axelor-gdpr/src/main/java/com/axelor/apps/gdpr/service/GdprProcessingRegisterService.java
- axelor-gdpr/src/main/java/com/axelor/apps/gdpr/service/GdprSearchEngineServiceImpl.java
- axelor-gdpr/src/main/java/com/axelor/apps/gdpr/service/response/GdprResponseErasureServiceImpl.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/expense/ExpenseProofFileServiceImpl.java
- axelor-stock/src/main/java/com/axelor/apps/stock/service/InventoryService.java
- libs.gradle
> Update studio SNAPSHOT dependency

- axelor-production/src/main/resources/views/StockMoveLine.xml
- axelor-stock/src/main/java/com/axelor/apps/stock/db/repo/StockMoveLineStockRepository.java
- axelor-stock/src/main/resources/views/StockMoveLine.xml
> Stock move: fixed TN creation from stock move

- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/module/SupplychainModule.java
> Remove duplicated binding

- axelor-business-production/src/main/java/com/axelor/apps/businessproduction/service/ManufOrderServiceBusinessImpl.java
- axelor-maintenance/src/main/java/com/axelor/apps/maintenance/module/MaintenanceModule.java
- axelor-maintenance/src/main/java/com/axelor/apps/maintenance/service/ManufOrderPlanServiceMaintenanceImpl.java
- axelor-maintenance/src/main/java/com/axelor/apps/maintenance/service/ManufOrderWorkflowMaintenanceServiceImpl.java
- axelor-production/src/main/java/com/axelor/apps/production/module/ProductionModule.java
- axelor-production/src/main/java/com/axelor/apps/production/rest/ManufOrderRestServiceImpl.java
- axelor-production/src/main/java/com/axelor/apps/production/service/manuforder/ManufOrderCreatePurchaseOrderService.java
- axelor-production/src/main/java/com/axelor/apps/production/service/manuforder/ManufOrderCreatePurchaseOrderServiceImpl.java
- axelor-production/src/main/java/com/axelor/apps/production/service/manuforder/ManufOrderPlanService.java
- axelor-production/src/main/java/com/axelor/apps/production/service/manuforder/ManufOrderPlanServiceImpl.java
- axelor-production/src/main/java/com/axelor/apps/production/service/manuforder/ManufOrderService.java
- axelor-production/src/main/java/com/axelor/apps/production/service/manuforder/ManufOrderServiceImpl.java
- axelor-production/src/main/java/com/axelor/apps/production/service/manuforder/ManufOrderWorkflowService.java
- axelor-production/src/main/java/com/axelor/apps/production/service/manuforder/ManufOrderWorkflowServiceImpl.java
- axelor-production/src/main/java/com/axelor/apps/production/web/ManufOrderController.java
> Refactor services related to manuf order plan

- axelor-account/src/main/resources/views/Invoice.xml
> Invoice: fix create refund opening a new tab

- axelor-base/src/main/java/com/axelor/apps/base/service/batch/BatchCountryAddressRecompute.java
- axelor-base/src/main/resources/domains/ExceptionOrigin.xml
- axelor-base/src/main/resources/views/Selects.xml
> Recompute address batch: fix exception management

- axelor-base/src/main/resources/views/Product.xml
- axelor-human-resource/src/main/resources/views/Product.xml
> Product: remove colWidths causing display issue

- axelor-base/src/main/java/com/axelor/apps/base/service/imports/ImportConfigurationCallableService.java
> ImportConfiguration: add RequestScope

- axelor-sale/src/main/java/com/axelor/apps/sale/module/SaleModule.java
- axelor-sale/src/main/java/com/axelor/apps/sale/service/configurator/ConfiguratorInitService.java
- axelor-sale/src/main/java/com/axelor/apps/sale/service/configurator/ConfiguratorInitServiceImpl.java
- axelor-sale/src/main/java/com/axelor/apps/sale/web/ConfiguratorCreatorController.java
- axelor-sale/src/main/resources/views/Configurator.xml
- axelor-sale/src/main/resources/views/ConfiguratorCreator.xml
fixed an issue where the configurator was not saved after clicking "test configurator" button.
RM75017
> Fixed issue when testing a configurator creator

- axelor-stock/src/main/java/com/axelor/apps/stock/service/StockMoveServiceImpl.java
- changelogs/unreleased/74048.yml
StockMove : Error when spliting in two
> RM74048 StockMove : Error when spliting in two

- changelogs/unreleased/update-studio.yml
- libs.gradle
> Update studio to 2.0.1

- axelor-business-project/src/main/resources/views/Selects.xml
> Fix duplicated selection

- axelor-account/src/main/java/com/axelor/apps/account/service/move/PaymentMoveLineDistributionServiceImpl.java
- axelor-account/src/main/java/com/axelor/apps/account/service/moveline/MoveLineTaxServiceImpl.java
> Tax management: refactor methods

- changelogs/unreleased/79103-update-studio.yml
- libs.gradle
> Update studio to 2.0.2

- axelor-business-project/src/main/resources/views/ProjectTask.xml
- axelor-human-resource/src/main/resources/views/ProjectPlanningTime.xml
- changelogs/unreleased/77763.yml
> dev-77763 ProjectPlanningTime: move if condition to on select action 

- axelor-base/src/main/java/com/axelor/apps/base/service/message/TemplateMessageServiceBaseImpl.java
- libs.gradle
> Upgrade to axelor-message 3.1

- axelor-bank-payment/src/main/resources/views/BankStatementLineAFB120.xml
- changelogs/unreleased/52455-bank-statement-cannew.yml
> Bank statement line: remove canNew from grid

- changelogs/unreleased/update-studio-81036.yml
- libs.gradle
> Update axelor-studio, utils, message to 3.1.1

- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/SaleOrderInvoiceServiceImpl.java
- changelogs/unreleased/80485.yml
> Sale order: fixed an issue preventing advance payment invoice creation

- axelor-account/src/main/resources/reports/AccountingReportType11.rptdesign
Add journal name and code after the title "Journal" in the report
> RM#80707: ACCOUNTINGREPORT : Add journal name on the Journal report (Type = 11)

- changelogs/unreleased/82425-studio-update.yml
- libs.gradle
> Update axelor-studio to 3.1.2

- axelor-mobile-settings/src/main/resources/i18n/messages_en.csv
- changelogs/unreleased/81221-add-missing-en-translation.yml
> Mobile settings: add missing english i18n for mobile menu order

- axelor-sale/src/main/java/com/axelor/apps/sale/rest/dto/ProductPostRequest.java
> Product price API: fixed swagger documentation

- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/invoice/generator/InvoiceLineGeneratorSupplyChain.java
- changelogs/unreleased/83525-fix-analytics-invoice-generation.yml
> ConcurrentModificationException when generating invoice with analytics

- axelor-account/src/main/java/com/axelor/apps/account/web/InvoiceController.java
- changelogs/unreleased/83124-fix-credit-note-title.yml
> Invoice: fixed credit note tab title

- axelor-human-resource/src/main/java/com/axelor/apps/hr/db/repo/TimesheetHRRepository.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/db/repo/TimesheetLineHRRepository.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/module/HumanResourceModule.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/timesheet/TimesheetLineComputeNameService.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/timesheet/TimesheetLineComputeNameServiceImpl.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/timesheet/TimesheetPeriodComputationServiceImpl.java
> Timesheet repository refactor injections

- axelor-account/src/main/java/com/axelor/apps/account/service/moveline/MoveLineCreateServiceImpl.java
- changelogs/unreleased/82876-fix-invoice-pack-ventilation.yml
> Invoice: fixed move generation with end of pack line

- axelor-budget/build.gradle
> Budget: remove dependency to axelor-test

- libs.gradle
> Upgrade to studio 3.3.0

- axelor-human-resource/src/main/resources/views/ExpenseLine.xml
- axelor-human-resource/src/main/resources/views/TimesheetLine.xml
> RM#84042 Change Site domain in ExpenseLine and TimesheetLine

- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/saleorder/SaleOrderInvoiceServiceImpl.java
> Sale order: improve check on existing invoices for invoicing wizard

- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/web/PurchaseOrderInvoiceController.java
- axelor-supplychain/src/main/resources/i18n/messages_fr.csv
- changelogs/unreleased/84748-purchase-order-invoicing.yml
> Purchase order: fixed check existing invoices when invoicing a PO

- axelor-budget/src/main/java/com/axelor/apps/budget/service/purchaseorder/PurchaseOrderInvoiceBudgetServiceImpl.java
- axelor-budget/src/main/java/com/axelor/apps/budget/service/saleorder/SaleOrderBudgetServiceImpl.java
- axelor-business-project/src/main/java/com/axelor/apps/businessproject/service/PurchaseOrderInvoiceProjectServiceImpl.java
- axelor-business-project/src/main/java/com/axelor/apps/businessproject/service/SaleOrderInvoiceProjectServiceImpl.java
- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/module/SupplychainModule.java
- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/PurchaseOrderInvoiceServiceImpl.java
- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/order/OrderInvoiceService.java
- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/order/OrderInvoiceServiceImpl.java
- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/saleorder/SaleOrderInvoiceServiceImpl.java
- axelor-supplychain/src/main/resources/i18n/messages_fr.csv
> Purchase order: improve check on existing invoice for invoicing wizard

- changelogs/unreleased/85131-update-studio.yml
- libs.gradle
> Update axelor-studio dependency to 3.1.4

- libs.gradle
> Update studio to 3.3.0 and message to 3.2.0

- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/db/repo/CartLineSupplychainRepository.java
> Cart: add a nullcheck in cart lines populate

- axelor-business-production/src/main/java/com/axelor/apps/businessproduction/rest/TimesheetLineBusinessRestController.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/module/HumanResourceModule.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/rest/TimesheetLinePostRequestHelper.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/rest/TimesheetLineRestController.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/rest/dto/TimesheetLinePostRequest.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/timesheet/TimesheetCreateService.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/timesheet/TimesheetCreateServiceImpl.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/timesheet/TimesheetQueryService.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/timesheet/TimesheetQueryServiceImpl.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/timesheet/TimesheetService.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/service/timesheet/TimesheetServiceImpl.java
- axelor-human-resource/src/main/java/com/axelor/apps/hr/web/timesheet/TimesheetLineController.java
> Timesheet line API: enable timesheet automatic creation

- axelor-sale/src/main/java/com/axelor/apps/sale/rest/SaleOrderRestController.java
> Sale Order API: add version check to /aos/sale-order/add-line/

- changelogs/unreleased/86487-update-message-dependency.yml
- changelogs/unreleased/86487-update-studio-dependency.yml
- changelogs/unreleased/86487-update-utils-dependency.yml
- libs.gradle
studio to 3.3.3, message to 3.2.2, utils to 3.3.0
RM86487
> Update studio dependencies

- changelogs/unreleased/88314-update-studio-dependency.yml
- libs.gradle
> Update axelor-studio dependency to 3.3.8

- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/invoice/InvoiceServiceSupplychainImpl.java
- changelogs/unreleased/88848-fixed-invoice-refund.yml
> fixed a regression preventing invoices refund

- axelor-account/src/main/java/com/axelor/apps/account/service/invoice/workflow/ventilate/VentilateAdvancePaymentRefundState.java
- changelogs/unreleased/88848-fixed-advance-payment-invoice-refund.yml
> Invoice: fixed advance payment refund

- changelogs/unreleased/89850-update-studio.yml
- libs.gradle
> Update axelor-studio dependency to 3.3.10

- changelogs/unreleased/89882-update-utils.yml
- libs.gradle
> Update axelor-utils to 3.3.2

- axelor-account/src/main/java/com/axelor/apps/account/service/fecimport/FECImporter.java
- changelogs/unreleased/90338-revert-FEC-import-accounted.yml
> Revert c314189dbed1d4d53615

- libs.gradle
> Update studio to 3.4.0

- axelor-human-resource/src/main/resources/i18n/messages_fr.csv
> App project: fix typo

- changelogs/unreleased/90828-update-axelor-studio.yml
- libs.gradle
> Update axelor-studio dependency to 3.3.11

- axelor-supplychain/src/main/java/com/axelor/apps/supplychain/service/PurchaseOrderStockServiceImpl.java
> Purchase order: fix stock move line generation

- libs.gradle
> Update studio dependency to 3.4.1

- axelor-base/src/main/java/com/axelor/apps/base/service/MailServiceBaseImpl.java
> fixed AOS not starting when axelor-helpdesk is not included

- axelor-production/src/main/java/com/axelor/apps/production/service/observer/SaleOrderLineProductionObserver.java
> Sale order: fixed NPE when opening sale order line form view

- changelogs/unreleased/93873-update-studio.yml
- libs.gradle
> Update studio to 3.4.2

- axelor-sale/src/main/java/com/axelor/apps/sale/web/SaleOrderLineController.java
- changelogs/unreleased/93092-sale-order-line-check.yml
> Sale order line: fixed warning display for stock availability

- axelor-stock/src/main/java/com/axelor/apps/stock/service/StockLocationServiceImpl.java
this will allow to remove the stockLocationLineList O2M.
RM93058
> Optimize change product locker API

- axelor-base/src/main/java/com/axelor/apps/base/service/PartnerServiceImpl.java
> fixed NPE after fix on partner registration code check

- changelogs/unreleased/96973-update-studio.yml
- libs.gradle
> Update axelor-studio to 3.4.5

- axelor-base/map-viewer/src/components/MarkerGroup/MarkerGroup.tsx
- axelor-base/map-viewer/src/index.css
> feat: add legend management inside the header filter

- axelor-base/map-viewer/src/components/LinkIcon/LinkIcon.tsx
- axelor-base/map-viewer/src/components/MarkerGroup/MarkerGroup.tsx
- axelor-base/map-viewer/src/components/MarkerPopup/MarkerPopup.tsx
> RM#100839: add view opening management when double clicking on a map popup
